2023-10-25 10:13:43,088 - INFO - [1m[37mPrograma Iniciado às [31m10:13:43[0m
2023-10-25 10:13:43,211 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-10-25 10:13:43,212 - ERROR -   warnings.warn("Image was not the expected size")
2023-10-25 10:14:19,640 - INFO - [1m[37mMapa da LINHA 4 - AMARELA iniciado às [32m10:13:42[0m
2023-10-25 10:14:22,493 - INFO - [1m[37mMapa da LINHA 3 - VERMELHA iniciado às [32m10:13:42[0m
2023-10-25 10:18:03,263 - INFO - [1m[37mPrograma Iniciado às [31m10:18:03[0m
2023-10-25 10:18:03,336 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-10-25 10:18:03,346 - ERROR -   warnings.warn("Image was not the expected size")
2023-10-25 10:18:19,242 - INFO - [1m[37mMapa da LINHA 5 - LILÁS iniciado às [32m10:18:03[0m
2023-10-25 10:18:27,074 - INFO - [1m[37mMapa da Rede iniciado às [32m10:18:01[0m
2023-10-26 17:34:50,187 - INFO - [1m[37mPrograma Iniciado às [31m17:34:50[0m
2023-10-26 17:34:50,294 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-10-26 17:34:50,295 - ERROR -   warnings.warn("Image was not the expected size")
2023-10-26 17:34:52,976 - WARNING - There was an error managing chrome (error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: Foi forçado o cancelamento de uma conexão existente pelo host remoto. (os error 10054)); using driver found in the cache
2023-10-26 17:35:12,604 - INFO - [1m[37mMapa da LINHA 1 - AZUL iniciado às [32m17:34:49[0m
2023-10-26 17:35:37,886 - INFO - [1m[37mMapa da LINHA 2 - VERDE iniciado às [32m17:34:49[0m
2023-10-26 17:35:46,839 - INFO - [1m[37mMapa da LINHA 3 - VERMELHA iniciado às [32m17:34:49[0m
2023-10-26 17:35:55,286 - INFO - [1m[37mMapa da LINHA 4 - AMARELA iniciado às [32m17:34:49[0m
2023-10-26 17:36:08,255 - INFO - [1m[37mMapa da LINHA 5 - LILÁS iniciado às [32m17:34:49[0m
2023-10-26 17:36:20,222 - INFO - [1m[37mMapa da LINHA 7 - RUBI iniciado às [32m17:34:49[0m
2023-10-26 17:36:27,558 - INFO - [1m[37mMapa da LINHA 8 - DIAMANTE iniciado às [32m17:34:49[0m
2023-10-26 17:36:34,766 - INFO - [1m[37mMapa da LINHA 9 - ESMERALDA iniciado às [32m17:34:49[0m
2023-10-26 17:37:45,431 - INFO - [1m[37mMapa da LINHA 4 - AMARELA iniciado às [32m17:34:49[0m
2023-10-26 17:37:53,167 - INFO - [1m[37mMapa da LINHA 5 - LILÁS iniciado às [32m17:34:49[0m
2023-10-26 17:38:01,750 - INFO - [1m[37mMapa da LINHA 10 - TURQUESA iniciado às [32m17:34:49[0m
2023-10-26 17:38:09,478 - INFO - [1m[37mMapa da LINHA 11 - CORAL iniciado às [32m17:34:49[0m
2023-10-26 17:38:16,726 - INFO - [1m[37mMapa da LINHA 12 - SAFIRA iniciado às [32m17:34:49[0m
2023-10-26 17:38:26,271 - INFO - [1m[37mMapa da LINHA 13 - JADE iniciado às [32m17:34:49[0m
2023-10-26 17:38:35,391 - INFO - [1m[37mMapa da LINHA 15 - PRATA iniciado às [32m17:34:49[0m
2023-10-26 17:39:01,918 - INFO - [1m[37mMapa da LINHA 12 - SAFIRA iniciado às [32m17:34:49[0m
2023-10-30 11:29:48,139 - INFO - [1m[37mPrograma Iniciado às [31m11:29:48[0m
2023-10-30 11:29:48,279 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-10-30 11:29:48,279 - ERROR -   warnings.warn("Image was not the expected size")
2023-10-30 11:30:22,636 - ERROR - Traceback (most recent call last):
2023-10-30 11:30:22,636 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 417, in <module>
2023-10-30 11:30:22,637 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-10-30 11:30:22,638 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-10-30 11:30:22,659 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-10-30 11:30:22,662 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-10-30 11:30:22,662 - ERROR - _tkinter
2023-10-30 11:30:22,662 - ERROR - .
2023-10-30 11:30:22,662 - ERROR - TclError
2023-10-30 11:30:22,662 - ERROR - :
2023-10-30 11:30:22,662 - ERROR - invalid command name ".!canvas"
2023-10-30 14:56:44,787 - INFO - [1m[37mPrograma Iniciado às [31m14:56:44[0m
2023-10-30 14:56:44,917 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-10-30 14:56:44,918 - ERROR -   warnings.warn("Image was not the expected size")
2023-10-30 14:57:41,281 - INFO - [1m[37mMapa da LINHA 4 - AMARELA iniciado às [32m14:56:44[0m
2023-10-30 14:57:50,141 - INFO - [1m[37mMapa da LINHA 3 - VERMELHA iniciado às [32m14:56:44[0m
2023-11-02 13:42:15,262 - INFO - [1m[37mPrograma Iniciado às [31m13:42:15[0m
2023-11-02 13:42:15,432 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-02 13:42:15,432 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-02 13:44:07,543 - INFO - [1m[37mPrograma Iniciado às [31m13:44:07[0m
2023-11-02 13:44:07,707 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-02 13:44:07,708 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-02 13:45:54,861 - ERROR - Traceback (most recent call last):
2023-11-02 13:45:54,862 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 417, in <module>
2023-11-02 13:45:54,874 - ERROR - canvas.itemconfigure(data_hora, text=datetime.now().strftime(
2023-11-02 13:45:54,875 - ERROR - ^
2023-11-02 13:45:54,875 - ERROR - ^
2023-11-02 13:45:54,875 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,876 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR - ^
2023-11-02 13:45:54,877 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-02 13:45:54,908 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-02 13:45:54,909 - ERROR - ^
2023-11-02 13:45:54,909 - ERROR - ^
2023-11-02 13:45:54,909 - ERROR - ^
2023-11-02 13:45:54,909 - ERROR - ^
2023-11-02 13:45:54,909 - ERROR - ^
2023-11-02 13:45:54,909 - ERROR - ^
2023-11-02 13:45:54,909 - ERROR - ^
2023-11-02 13:45:54,909 - ERROR - ^
2023-11-02 13:45:54,909 - ERROR - ^
2023-11-02 13:45:54,909 - ERROR - ^
2023-11-02 13:45:54,909 - ERROR - ^
2023-11-02 13:45:54,909 - ERROR - ^
2023-11-02 13:45:54,909 - ERROR - ^
2023-11-02 13:45:54,909 - ERROR - ^
2023-11-02 13:45:54,909 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,910 - ERROR - ^
2023-11-02 13:45:54,911 - ERROR - ^
2023-11-02 13:45:54,911 - ERROR - ^
2023-11-02 13:45:54,911 - ERROR - ^
2023-11-02 13:45:54,911 - ERROR - ^
2023-11-02 13:45:54,911 - ERROR - ^
2023-11-02 13:45:54,911 - ERROR - ^
2023-11-02 13:45:54,911 - ERROR - ^
2023-11-02 13:45:54,911 - ERROR - ^
2023-11-02 13:45:54,911 - ERROR - ^
2023-11-02 13:45:54,911 - ERROR - ^
2023-11-02 13:45:54,911 - ERROR - ^
2023-11-02 13:45:54,911 - ERROR - ^
2023-11-02 13:45:54,911 - ERROR - ^
2023-11-02 13:45:54,911 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-02 13:45:54,912 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-02 13:45:54,912 - ERROR - _tkinter
2023-11-02 13:45:54,912 - ERROR - .
2023-11-02 13:45:54,912 - ERROR - TclError
2023-11-02 13:45:54,912 - ERROR - :
2023-11-02 13:45:54,912 - ERROR - invalid command name ".!canvas"
2023-11-02 13:45:57,542 - INFO - [1m[37mPrograma Iniciado às [31m13:45:57[0m
2023-11-02 13:45:57,626 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-02 13:45:57,627 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-02 13:52:44,885 - INFO - [1m[37mPrograma Iniciado às [31m13:52:44[0m
2023-11-02 13:52:44,970 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-02 13:52:44,971 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-02 13:52:56,528 - INFO - Linha 9-Esmeralda: Devido à manutenção programada no sistema elétrico, a circulação dos trens está ocorrendo por via única entre as estações Cidade Jardim e Villa Lobos-Jaguaré, gerando maiores intervalos.
2023-11-02 13:52:56,529 - INFO - TURQUESA: A circulação de trens entre as estações Rio Grande Da Serra e Mauá está interrompida. O percurso está sendo feito por ônibus estacionados em frente às estações.
2023-11-02 13:53:14,391 - ERROR - Traceback (most recent call last):
2023-11-02 13:53:14,392 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 416, in <module>
2023-11-02 13:53:14,394 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-02 13:53:14,394 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-02 13:53:14,396 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-02 13:53:14,396 - ERROR - ^
2023-11-02 13:53:14,396 - ERROR - ^
2023-11-02 13:53:14,397 - ERROR - ^
2023-11-02 13:53:14,397 - ERROR - ^
2023-11-02 13:53:14,397 - ERROR - ^
2023-11-02 13:53:14,397 - ERROR - ^
2023-11-02 13:53:14,397 - ERROR - ^
2023-11-02 13:53:14,397 - ERROR - ^
2023-11-02 13:53:14,398 - ERROR - ^
2023-11-02 13:53:14,398 - ERROR - ^
2023-11-02 13:53:14,398 - ERROR - ^
2023-11-02 13:53:14,398 - ERROR - ^
2023-11-02 13:53:14,398 - ERROR - ^
2023-11-02 13:53:14,399 - ERROR - ^
2023-11-02 13:53:14,399 - ERROR - ^
2023-11-02 13:53:14,399 - ERROR - ^
2023-11-02 13:53:14,399 - ERROR - ^
2023-11-02 13:53:14,400 - ERROR - ^
2023-11-02 13:53:14,400 - ERROR - ^
2023-11-02 13:53:14,400 - ERROR - ^
2023-11-02 13:53:14,400 - ERROR - ^
2023-11-02 13:53:14,400 - ERROR - ^
2023-11-02 13:53:14,401 - ERROR - ^
2023-11-02 13:53:14,401 - ERROR - ^
2023-11-02 13:53:14,401 - ERROR - ^
2023-11-02 13:53:14,401 - ERROR - ^
2023-11-02 13:53:14,402 - ERROR - ^
2023-11-02 13:53:14,402 - ERROR - ^
2023-11-02 13:53:14,402 - ERROR - ^
2023-11-02 13:53:14,402 - ERROR - ^
2023-11-02 13:53:14,402 - ERROR - ^
2023-11-02 13:53:14,402 - ERROR - ^
2023-11-02 13:53:14,403 - ERROR - ^
2023-11-02 13:53:14,403 - ERROR - ^
2023-11-02 13:53:14,403 - ERROR - ^
2023-11-02 13:53:14,403 - ERROR - ^
2023-11-02 13:53:14,403 - ERROR - ^
2023-11-02 13:53:14,403 - ERROR - ^
2023-11-02 13:53:14,404 - ERROR - ^
2023-11-02 13:53:14,404 - ERROR - ^
2023-11-02 13:53:14,404 - ERROR - ^
2023-11-02 13:53:14,404 - ERROR - ^
2023-11-02 13:53:14,404 - ERROR - ^
2023-11-02 13:53:14,404 - ERROR - ^
2023-11-02 13:53:14,405 - ERROR - ^
2023-11-02 13:53:14,405 - ERROR - ^
2023-11-02 13:53:14,405 - ERROR - ^
2023-11-02 13:53:14,405 - ERROR - ^
2023-11-02 13:53:14,405 - ERROR - ^
2023-11-02 13:53:14,406 - ERROR - ^
2023-11-02 13:53:14,406 - ERROR - ^
2023-11-02 13:53:14,406 - ERROR - ^
2023-11-02 13:53:14,406 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-02 13:53:14,407 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-02 13:53:14,407 - ERROR - _tkinter
2023-11-02 13:53:14,407 - ERROR - .
2023-11-02 13:53:14,407 - ERROR - TclError
2023-11-02 13:53:14,407 - ERROR - :
2023-11-02 13:53:14,407 - ERROR - invalid command name ".!canvas"
2023-11-02 13:53:31,482 - INFO - [1m[37mPrograma Iniciado às [31m13:53:31[0m
2023-11-02 13:53:31,555 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-02 13:53:31,555 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-02 13:53:43,370 - INFO - ['Linha 9-Esmeralda: Devido à manutenção programada no sistema elétrico, a circulação dos trens está ocorrendo por via única entre as estações Cidade Jardim e Villa Lobos-Jaguaré, gerando maiores intervalos.', 'TURQUESA: A circulação de trens entre as estações Rio Grande Da Serra e Mauá está interrompida. O percurso está sendo feito por ônibus estacionados em frente às estações.']
2023-11-02 13:53:43,370 - INFO - ['Linha 9-Esmeralda: Devido à manutenção programada no sistema elétrico, a circulação dos trens está ocorrendo por via única entre as estações Cidade Jardim e Villa Lobos-Jaguaré, gerando maiores intervalos.', 'TURQUESA: A circulação de trens entre as estações Rio Grande Da Serra e Mauá está interrompida. O percurso está sendo feito por ônibus estacionados em frente às estações.']
2023-11-02 13:54:15,849 - INFO - [1m[37mPrograma Iniciado às [31m13:54:15[0m
2023-11-02 13:54:15,943 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-02 13:54:15,944 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-02 13:54:27,409 - INFO - TURQUESA: A circulação de trens entre as estações Rio Grande Da Serra e Mauá está interrompida. O percurso está sendo feito por ônibus estacionados em frente às estações.
2023-11-02 13:55:23,100 - INFO - <function status at 0x0000025C6ED55440>
2023-11-02 13:55:23,192 - INFO - [1m[37mPrograma Iniciado às [31m13:55:23[0m
2023-11-02 13:55:23,306 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-02 13:55:23,307 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-02 13:56:04,467 - ERROR - Traceback (most recent call last):
2023-11-02 13:56:04,468 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 418, in <module>
2023-11-02 13:56:04,469 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-02 13:56:04,470 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-02 13:56:04,472 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-02 13:56:04,472 - ERROR - ^
2023-11-02 13:56:04,472 - ERROR - ^
2023-11-02 13:56:04,473 - ERROR - ^
2023-11-02 13:56:04,473 - ERROR - ^
2023-11-02 13:56:04,473 - ERROR - ^
2023-11-02 13:56:04,473 - ERROR - ^
2023-11-02 13:56:04,473 - ERROR - ^
2023-11-02 13:56:04,474 - ERROR - ^
2023-11-02 13:56:04,474 - ERROR - ^
2023-11-02 13:56:04,474 - ERROR - ^
2023-11-02 13:56:04,474 - ERROR - ^
2023-11-02 13:56:04,474 - ERROR - ^
2023-11-02 13:56:04,475 - ERROR - ^
2023-11-02 13:56:04,475 - ERROR - ^
2023-11-02 13:56:04,475 - ERROR - ^
2023-11-02 13:56:04,475 - ERROR - ^
2023-11-02 13:56:04,475 - ERROR - ^
2023-11-02 13:56:04,476 - ERROR - ^
2023-11-02 13:56:04,476 - ERROR - ^
2023-11-02 13:56:04,476 - ERROR - ^
2023-11-02 13:56:04,476 - ERROR - ^
2023-11-02 13:56:04,477 - ERROR - ^
2023-11-02 13:56:04,477 - ERROR - ^
2023-11-02 13:56:04,477 - ERROR - ^
2023-11-02 13:56:04,477 - ERROR - ^
2023-11-02 13:56:04,477 - ERROR - ^
2023-11-02 13:56:04,477 - ERROR - ^
2023-11-02 13:56:04,477 - ERROR - ^
2023-11-02 13:56:04,477 - ERROR - ^
2023-11-02 13:56:04,477 - ERROR - ^
2023-11-02 13:56:04,477 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,478 - ERROR - ^
2023-11-02 13:56:04,479 - ERROR - ^
2023-11-02 13:56:04,479 - ERROR - ^
2023-11-02 13:56:04,479 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-02 13:56:04,480 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-02 13:56:04,480 - ERROR - _tkinter
2023-11-02 13:56:04,480 - ERROR - .
2023-11-02 13:56:04,480 - ERROR - TclError
2023-11-02 13:56:04,480 - ERROR - :
2023-11-02 13:56:04,480 - ERROR - invalid command name ".!canvas"
2023-11-02 13:57:14,229 - INFO - [1m[37mPrograma Iniciado às [31m13:57:14[0m
2023-11-02 13:57:14,371 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-02 13:57:14,372 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-02 13:57:26,105 - INFO - Linha 9-Esmeralda: Devido à manutenção programada no sistema elétrico, a circulação dos trens está ocorrendo por via única entre as estações Cidade Jardim e Villa Lobos-Jaguaré, gerando maiores intervalos.
2023-11-02 13:57:26,105 - INFO - TURQUESA: A circulação de trens entre as estações Rio Grande Da Serra e Mauá está interrompida. O percurso está sendo feito por ônibus estacionados em frente às estações.
2023-11-02 13:57:32,121 - ERROR - Traceback (most recent call last):
2023-11-02 13:57:32,121 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 417, in <module>
2023-11-02 13:57:32,122 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-02 13:57:32,123 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-02 13:57:32,124 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-02 13:57:32,124 - ERROR - ^
2023-11-02 13:57:32,124 - ERROR - ^
2023-11-02 13:57:32,124 - ERROR - ^
2023-11-02 13:57:32,124 - ERROR - ^
2023-11-02 13:57:32,124 - ERROR - ^
2023-11-02 13:57:32,125 - ERROR - ^
2023-11-02 13:57:32,125 - ERROR - ^
2023-11-02 13:57:32,125 - ERROR - ^
2023-11-02 13:57:32,125 - ERROR - ^
2023-11-02 13:57:32,125 - ERROR - ^
2023-11-02 13:57:32,125 - ERROR - ^
2023-11-02 13:57:32,125 - ERROR - ^
2023-11-02 13:57:32,126 - ERROR - ^
2023-11-02 13:57:32,126 - ERROR - ^
2023-11-02 13:57:32,126 - ERROR - ^
2023-11-02 13:57:32,127 - ERROR - ^
2023-11-02 13:57:32,127 - ERROR - ^
2023-11-02 13:57:32,127 - ERROR - ^
2023-11-02 13:57:32,127 - ERROR - ^
2023-11-02 13:57:32,128 - ERROR - ^
2023-11-02 13:57:32,128 - ERROR - ^
2023-11-02 13:57:32,128 - ERROR - ^
2023-11-02 13:57:32,128 - ERROR - ^
2023-11-02 13:57:32,129 - ERROR - ^
2023-11-02 13:57:32,129 - ERROR - ^
2023-11-02 13:57:32,129 - ERROR - ^
2023-11-02 13:57:32,129 - ERROR - ^
2023-11-02 13:57:32,129 - ERROR - ^
2023-11-02 13:57:32,129 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR - ^
2023-11-02 13:57:32,130 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-02 13:57:32,131 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-02 13:57:32,131 - ERROR - _tkinter
2023-11-02 13:57:32,131 - ERROR - .
2023-11-02 13:57:32,131 - ERROR - TclError
2023-11-02 13:57:32,131 - ERROR - :
2023-11-02 13:57:32,131 - ERROR - invalid command name ".!canvas"
2023-11-02 14:04:32,581 - INFO - [1m[37mPrograma Iniciado às [31m14:04:32[0m
2023-11-02 14:04:32,668 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-02 14:04:32,669 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-02 14:04:44,494 - INFO - Linha 9-Esmeralda: Devido à manutenção programada no sistema elétrico, a circulação dos trens está ocorrendo por via única entre as estações Cidade Jardim e Villa Lobos-Jaguaré, gerando maiores intervalos.
2023-11-02 14:04:44,494 - INFO - TURQUESA: A circulação de trens entre as estações Rio Grande Da Serra e Mauá está interrompida. O percurso está sendo feito por ônibus estacionados em frente às estações.
2023-11-02 14:04:50,641 - ERROR - Traceback (most recent call last):
2023-11-02 14:04:50,641 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 417, in <module>
2023-11-02 14:04:50,643 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-02 14:04:50,643 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-02 14:04:50,645 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-02 14:04:50,646 - ERROR - ^
2023-11-02 14:04:50,646 - ERROR - ^
2023-11-02 14:04:50,646 - ERROR - ^
2023-11-02 14:04:50,646 - ERROR - ^
2023-11-02 14:04:50,646 - ERROR - ^
2023-11-02 14:04:50,647 - ERROR - ^
2023-11-02 14:04:50,647 - ERROR - ^
2023-11-02 14:04:50,647 - ERROR - ^
2023-11-02 14:04:50,647 - ERROR - ^
2023-11-02 14:04:50,648 - ERROR - ^
2023-11-02 14:04:50,648 - ERROR - ^
2023-11-02 14:04:50,648 - ERROR - ^
2023-11-02 14:04:50,648 - ERROR - ^
2023-11-02 14:04:50,648 - ERROR - ^
2023-11-02 14:04:50,648 - ERROR - ^
2023-11-02 14:04:50,649 - ERROR - ^
2023-11-02 14:04:50,649 - ERROR - ^
2023-11-02 14:04:50,649 - ERROR - ^
2023-11-02 14:04:50,649 - ERROR - ^
2023-11-02 14:04:50,649 - ERROR - ^
2023-11-02 14:04:50,649 - ERROR - ^
2023-11-02 14:04:50,649 - ERROR - ^
2023-11-02 14:04:50,650 - ERROR - ^
2023-11-02 14:04:50,650 - ERROR - ^
2023-11-02 14:04:50,650 - ERROR - ^
2023-11-02 14:04:50,650 - ERROR - ^
2023-11-02 14:04:50,650 - ERROR - ^
2023-11-02 14:04:50,650 - ERROR - ^
2023-11-02 14:04:50,650 - ERROR - ^
2023-11-02 14:04:50,651 - ERROR - ^
2023-11-02 14:04:50,651 - ERROR - ^
2023-11-02 14:04:50,651 - ERROR - ^
2023-11-02 14:04:50,651 - ERROR - ^
2023-11-02 14:04:50,651 - ERROR - ^
2023-11-02 14:04:50,651 - ERROR - ^
2023-11-02 14:04:50,652 - ERROR - ^
2023-11-02 14:04:50,652 - ERROR - ^
2023-11-02 14:04:50,652 - ERROR - ^
2023-11-02 14:04:50,652 - ERROR - ^
2023-11-02 14:04:50,652 - ERROR - ^
2023-11-02 14:04:50,652 - ERROR - ^
2023-11-02 14:04:50,652 - ERROR - ^
2023-11-02 14:04:50,653 - ERROR - ^
2023-11-02 14:04:50,653 - ERROR - ^
2023-11-02 14:04:50,653 - ERROR - ^
2023-11-02 14:04:50,653 - ERROR - ^
2023-11-02 14:04:50,653 - ERROR - ^
2023-11-02 14:04:50,653 - ERROR - ^
2023-11-02 14:04:50,653 - ERROR - ^
2023-11-02 14:04:50,653 - ERROR - ^
2023-11-02 14:04:50,653 - ERROR - ^
2023-11-02 14:04:50,653 - ERROR - ^
2023-11-02 14:04:50,653 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-02 14:04:50,654 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-02 14:04:50,654 - ERROR - _tkinter
2023-11-02 14:04:50,654 - ERROR - .
2023-11-02 14:04:50,654 - ERROR - TclError
2023-11-02 14:04:50,654 - ERROR - :
2023-11-02 14:04:50,654 - ERROR - invalid command name ".!canvas"
2023-11-02 14:08:53,223 - INFO - [1m[37mPrograma Iniciado às [31m14:08:53[0m
2023-11-02 14:08:53,319 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-02 14:08:53,320 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-02 14:09:04,811 - INFO - Linha 9-Esmeralda: Devido à manutenção programada no sistema elétrico, a circulação dos trens está ocorrendo por via única entre as estações Cidade Jardim e Villa Lobos-Jaguaré, gerando maiores intervalos.
2023-11-02 14:09:04,811 - INFO - TURQUESA: A circulação de trens entre as estações Rio Grande Da Serra e Mauá está interrompida. O percurso está sendo feito por ônibus estacionados em frente às estações.
2023-11-02 14:09:15,316 - ERROR - Traceback (most recent call last):
2023-11-02 14:09:15,316 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 417, in <module>
2023-11-02 14:09:15,318 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-02 14:09:15,319 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-02 14:09:15,321 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-02 14:09:15,322 - ERROR - ^
2023-11-02 14:09:15,322 - ERROR - ^
2023-11-02 14:09:15,322 - ERROR - ^
2023-11-02 14:09:15,323 - ERROR - ^
2023-11-02 14:09:15,323 - ERROR - ^
2023-11-02 14:09:15,323 - ERROR - ^
2023-11-02 14:09:15,323 - ERROR - ^
2023-11-02 14:09:15,323 - ERROR - ^
2023-11-02 14:09:15,324 - ERROR - ^
2023-11-02 14:09:15,324 - ERROR - ^
2023-11-02 14:09:15,324 - ERROR - ^
2023-11-02 14:09:15,324 - ERROR - ^
2023-11-02 14:09:15,325 - ERROR - ^
2023-11-02 14:09:15,325 - ERROR - ^
2023-11-02 14:09:15,325 - ERROR - ^
2023-11-02 14:09:15,325 - ERROR - ^
2023-11-02 14:09:15,325 - ERROR - ^
2023-11-02 14:09:15,326 - ERROR - ^
2023-11-02 14:09:15,326 - ERROR - ^
2023-11-02 14:09:15,326 - ERROR - ^
2023-11-02 14:09:15,326 - ERROR - ^
2023-11-02 14:09:15,326 - ERROR - ^
2023-11-02 14:09:15,326 - ERROR - ^
2023-11-02 14:09:15,327 - ERROR - ^
2023-11-02 14:09:15,327 - ERROR - ^
2023-11-02 14:09:15,327 - ERROR - ^
2023-11-02 14:09:15,327 - ERROR - ^
2023-11-02 14:09:15,327 - ERROR - ^
2023-11-02 14:09:15,328 - ERROR - ^
2023-11-02 14:09:15,328 - ERROR - ^
2023-11-02 14:09:15,328 - ERROR - ^
2023-11-02 14:09:15,328 - ERROR - ^
2023-11-02 14:09:15,328 - ERROR - ^
2023-11-02 14:09:15,328 - ERROR - ^
2023-11-02 14:09:15,329 - ERROR - ^
2023-11-02 14:09:15,329 - ERROR - ^
2023-11-02 14:09:15,329 - ERROR - ^
2023-11-02 14:09:15,329 - ERROR - ^
2023-11-02 14:09:15,329 - ERROR - ^
2023-11-02 14:09:15,329 - ERROR - ^
2023-11-02 14:09:15,329 - ERROR - ^
2023-11-02 14:09:15,330 - ERROR - ^
2023-11-02 14:09:15,330 - ERROR - ^
2023-11-02 14:09:15,330 - ERROR - ^
2023-11-02 14:09:15,330 - ERROR - ^
2023-11-02 14:09:15,330 - ERROR - ^
2023-11-02 14:09:15,331 - ERROR - ^
2023-11-02 14:09:15,331 - ERROR - ^
2023-11-02 14:09:15,331 - ERROR - ^
2023-11-02 14:09:15,331 - ERROR - ^
2023-11-02 14:09:15,332 - ERROR - ^
2023-11-02 14:09:15,332 - ERROR - ^
2023-11-02 14:09:15,332 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-02 14:09:15,332 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-02 14:09:15,333 - ERROR - _tkinter
2023-11-02 14:09:15,333 - ERROR - .
2023-11-02 14:09:15,333 - ERROR - TclError
2023-11-02 14:09:15,333 - ERROR - :
2023-11-02 14:09:15,333 - ERROR - invalid command name ".!canvas"
2023-11-02 14:13:44,713 - INFO - [1m[37mPrograma Iniciado às [31m14:13:44[0m
2023-11-02 14:13:44,840 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-02 14:13:44,840 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-02 14:13:56,276 - INFO - Linha 9-Esmeralda: Devido à manutenção programada no sistema elétrico, a circulação dos trens está ocorrendo por via única entre as estações Cidade Jardim e Villa Lobos-Jaguaré, gerando maiores intervalos.
2023-11-02 14:13:56,277 - INFO - TURQUESA: A circulação de trens entre as estações Rio Grande Da Serra e Mauá está interrompida. O percurso está sendo feito por ônibus estacionados em frente às estações.
2023-11-02 14:14:28,222 - ERROR - Traceback (most recent call last):
2023-11-02 14:14:28,223 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 417, in <module>
2023-11-02 14:14:28,224 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-02 14:14:28,224 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-02 14:14:28,225 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-02 14:14:28,225 - ERROR - ^
2023-11-02 14:14:28,225 - ERROR - ^
2023-11-02 14:14:28,226 - ERROR - ^
2023-11-02 14:14:28,226 - ERROR - ^
2023-11-02 14:14:28,226 - ERROR - ^
2023-11-02 14:14:28,226 - ERROR - ^
2023-11-02 14:14:28,226 - ERROR - ^
2023-11-02 14:14:28,226 - ERROR - ^
2023-11-02 14:14:28,226 - ERROR - ^
2023-11-02 14:14:28,227 - ERROR - ^
2023-11-02 14:14:28,227 - ERROR - ^
2023-11-02 14:14:28,227 - ERROR - ^
2023-11-02 14:14:28,227 - ERROR - ^
2023-11-02 14:14:28,227 - ERROR - ^
2023-11-02 14:14:28,227 - ERROR - ^
2023-11-02 14:14:28,228 - ERROR - ^
2023-11-02 14:14:28,228 - ERROR - ^
2023-11-02 14:14:28,228 - ERROR - ^
2023-11-02 14:14:28,228 - ERROR - ^
2023-11-02 14:14:28,228 - ERROR - ^
2023-11-02 14:14:28,228 - ERROR - ^
2023-11-02 14:14:28,229 - ERROR - ^
2023-11-02 14:14:28,229 - ERROR - ^
2023-11-02 14:14:28,229 - ERROR - ^
2023-11-02 14:14:28,229 - ERROR - ^
2023-11-02 14:14:28,229 - ERROR - ^
2023-11-02 14:14:28,229 - ERROR - ^
2023-11-02 14:14:28,230 - ERROR - ^
2023-11-02 14:14:28,230 - ERROR - ^
2023-11-02 14:14:28,230 - ERROR - ^
2023-11-02 14:14:28,230 - ERROR - ^
2023-11-02 14:14:28,230 - ERROR - ^
2023-11-02 14:14:28,230 - ERROR - ^
2023-11-02 14:14:28,230 - ERROR - ^
2023-11-02 14:14:28,231 - ERROR - ^
2023-11-02 14:14:28,231 - ERROR - ^
2023-11-02 14:14:28,231 - ERROR - ^
2023-11-02 14:14:28,231 - ERROR - ^
2023-11-02 14:14:28,231 - ERROR - ^
2023-11-02 14:14:28,231 - ERROR - ^
2023-11-02 14:14:28,231 - ERROR - ^
2023-11-02 14:14:28,232 - ERROR - ^
2023-11-02 14:14:28,232 - ERROR - ^
2023-11-02 14:14:28,232 - ERROR - ^
2023-11-02 14:14:28,232 - ERROR - ^
2023-11-02 14:14:28,232 - ERROR - ^
2023-11-02 14:14:28,232 - ERROR - ^
2023-11-02 14:14:28,232 - ERROR - ^
2023-11-02 14:14:28,233 - ERROR - ^
2023-11-02 14:14:28,233 - ERROR - ^
2023-11-02 14:14:28,233 - ERROR - ^
2023-11-02 14:14:28,233 - ERROR - ^
2023-11-02 14:14:28,233 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-02 14:14:28,234 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-02 14:14:28,234 - ERROR - _tkinter
2023-11-02 14:14:28,234 - ERROR - .
2023-11-02 14:14:28,234 - ERROR - TclError
2023-11-02 14:14:28,234 - ERROR - :
2023-11-02 14:14:28,234 - ERROR - invalid command name ".!canvas"
2023-11-02 14:14:46,042 - INFO - [1m[37mPrograma Iniciado às [31m14:14:46[0m
2023-11-02 14:14:46,135 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-02 14:14:46,135 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-02 14:14:57,461 - INFO - Linha 9-Esmeralda: Devido à manutenção programada no sistema elétrico, a circulação dos trens está ocorrendo por via única entre as estações Cidade Jardim e Villa Lobos-Jaguaré, gerando maiores intervalos.
2023-11-02 14:14:57,462 - INFO - TURQUESA: A circulação de trens entre as estações Rio Grande Da Serra e Mauá está interrompida. O percurso está sendo feito por ônibus estacionados em frente às estações.
2023-11-02 14:15:05,400 - ERROR - Traceback (most recent call last):
2023-11-02 14:15:05,400 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 418, in <module>
2023-11-02 14:15:05,401 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-02 14:15:05,401 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-02 14:15:05,402 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-02 14:15:05,402 - ERROR - ^
2023-11-02 14:15:05,402 - ERROR - ^
2023-11-02 14:15:05,402 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,403 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,404 - ERROR - ^
2023-11-02 14:15:05,405 - ERROR - ^
2023-11-02 14:15:05,405 - ERROR - ^
2023-11-02 14:15:05,405 - ERROR - ^
2023-11-02 14:15:05,405 - ERROR - ^
2023-11-02 14:15:05,405 - ERROR - ^
2023-11-02 14:15:05,405 - ERROR - ^
2023-11-02 14:15:05,405 - ERROR - ^
2023-11-02 14:15:05,405 - ERROR - ^
2023-11-02 14:15:05,405 - ERROR - ^
2023-11-02 14:15:05,405 - ERROR - ^
2023-11-02 14:15:05,405 - ERROR - ^
2023-11-02 14:15:05,405 - ERROR - ^
2023-11-02 14:15:05,405 - ERROR - ^
2023-11-02 14:15:05,405 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-02 14:15:05,406 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-02 14:15:05,406 - ERROR - _tkinter
2023-11-02 14:15:05,406 - ERROR - .
2023-11-02 14:15:05,406 - ERROR - TclError
2023-11-02 14:15:05,406 - ERROR - :
2023-11-02 14:15:05,406 - ERROR - invalid command name ".!canvas"
2023-11-02 14:15:13,762 - INFO - [1m[37mPrograma Iniciado às [31m14:15:13[0m
2023-11-02 14:15:13,836 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-02 14:15:13,836 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-02 14:15:26,166 - ERROR - Traceback (most recent call last):
2023-11-02 14:15:26,166 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 415, in <module>
2023-11-02 14:15:26,166 - ERROR - atualizar_status()
2023-11-02 14:15:26,166 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 101, in atualizar_status
2023-11-02 14:15:26,167 - ERROR - label_msg.config1(text=mensagem, fg="yellow", bg="#333333")
2023-11-02 14:15:26,167 - ERROR - ^
2023-11-02 14:15:26,167 - ERROR - ^
2023-11-02 14:15:26,167 - ERROR - ^
2023-11-02 14:15:26,167 - ERROR - ^
2023-11-02 14:15:26,167 - ERROR - ^
2023-11-02 14:15:26,167 - ERROR - ^
2023-11-02 14:15:26,167 - ERROR - ^
2023-11-02 14:15:26,167 - ERROR - ^
2023-11-02 14:15:26,167 - ERROR - ^
2023-11-02 14:15:26,167 - ERROR - ^
2023-11-02 14:15:26,167 - ERROR - ^
2023-11-02 14:15:26,167 - ERROR - ^
2023-11-02 14:15:26,167 - ERROR - ^
2023-11-02 14:15:26,167 - ERROR - ^
2023-11-02 14:15:26,167 - ERROR - ^
2023-11-02 14:15:26,167 - ERROR - ^
2023-11-02 14:15:26,168 - ERROR - ^
2023-11-02 14:15:26,168 - ERROR - AttributeError
2023-11-02 14:15:26,168 - ERROR - :
2023-11-02 14:15:26,168 - ERROR - 'Label' object has no attribute 'config1'
2023-11-02 14:15:26,168 - ERROR - . Did you mean: '
2023-11-02 14:15:26,168 - ERROR - config
2023-11-02 14:15:26,168 - ERROR - '?
2023-11-03 13:30:34,528 - INFO - [1m[37mPrograma Iniciado às [31m13:30:34[0m
2023-11-03 13:30:34,753 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 13:30:34,754 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 13:30:48,350 - INFO - Nenhuma ocorrência no momento.
2023-11-03 13:31:36,432 - ERROR - Traceback (most recent call last):
2023-11-03 13:31:36,432 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 417, in <module>
2023-11-03 13:31:36,435 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 13:31:36,435 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 13:31:36,454 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 13:31:36,454 - ERROR - ^
2023-11-03 13:31:36,454 - ERROR - ^
2023-11-03 13:31:36,455 - ERROR - ^
2023-11-03 13:31:36,455 - ERROR - ^
2023-11-03 13:31:36,455 - ERROR - ^
2023-11-03 13:31:36,455 - ERROR - ^
2023-11-03 13:31:36,455 - ERROR - ^
2023-11-03 13:31:36,455 - ERROR - ^
2023-11-03 13:31:36,455 - ERROR - ^
2023-11-03 13:31:36,455 - ERROR - ^
2023-11-03 13:31:36,456 - ERROR - ^
2023-11-03 13:31:36,456 - ERROR - ^
2023-11-03 13:31:36,456 - ERROR - ^
2023-11-03 13:31:36,456 - ERROR - ^
2023-11-03 13:31:36,456 - ERROR - ^
2023-11-03 13:31:36,456 - ERROR - ^
2023-11-03 13:31:36,456 - ERROR - ^
2023-11-03 13:31:36,456 - ERROR - ^
2023-11-03 13:31:36,457 - ERROR - ^
2023-11-03 13:31:36,457 - ERROR - ^
2023-11-03 13:31:36,457 - ERROR - ^
2023-11-03 13:31:36,457 - ERROR - ^
2023-11-03 13:31:36,457 - ERROR - ^
2023-11-03 13:31:36,457 - ERROR - ^
2023-11-03 13:31:36,457 - ERROR - ^
2023-11-03 13:31:36,457 - ERROR - ^
2023-11-03 13:31:36,458 - ERROR - ^
2023-11-03 13:31:36,458 - ERROR - ^
2023-11-03 13:31:36,458 - ERROR - ^
2023-11-03 13:31:36,458 - ERROR - ^
2023-11-03 13:31:36,458 - ERROR - ^
2023-11-03 13:31:36,458 - ERROR - ^
2023-11-03 13:31:36,458 - ERROR - ^
2023-11-03 13:31:36,458 - ERROR - ^
2023-11-03 13:31:36,458 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR - ^
2023-11-03 13:31:36,459 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 13:31:36,460 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 13:31:36,460 - ERROR - _tkinter
2023-11-03 13:31:36,460 - ERROR - .
2023-11-03 13:31:36,460 - ERROR - TclError
2023-11-03 13:31:36,460 - ERROR - :
2023-11-03 13:31:36,460 - ERROR - invalid command name ".!canvas"
2023-11-03 13:31:38,434 - INFO - [1m[37mPrograma Iniciado às [31m13:31:38[0m
2023-11-03 13:31:38,519 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 13:31:38,520 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:19:34,491 - INFO - [1m[37mPrograma Iniciado às [31m18:19:34[0m
2023-11-03 18:19:34,637 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:19:34,637 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:19:37,380 - WARNING - There was an error managing chrome (error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: Foi forçado o cancelamento de uma conexão existente pelo host remoto. (os error 10054)); using driver found in the cache
2023-11-03 18:19:47,469 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:19:47,470 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:19:47,470 - INFO - CORAL: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Guaianases e Estudantes , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:19:47,471 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:24:09,737 - INFO - [1m[37mPrograma Iniciado às [31m18:24:09[0m
2023-11-03 18:24:09,798 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:24:09,798 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:24:20,952 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:24:20,953 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:24:20,953 - INFO - CORAL: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Guaianases e Estudantes , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:24:20,953 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:24:30,969 - INFO - [1m[37mPrograma Iniciado às [31m18:24:30[0m
2023-11-03 18:24:31,013 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:24:31,014 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:24:41,466 - ERROR - Traceback (most recent call last):
2023-11-03 18:24:41,466 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 419, in <module>
2023-11-03 18:24:41,466 - ERROR - atualizar_status()
2023-11-03 18:24:41,466 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 100, in atualizar_status
2023-11-03 18:24:41,466 - ERROR - text_widget.insert('end', mensagem + '\n', fg="yellow", bg="#333333")
2023-11-03 18:24:41,466 - ERROR - TypeError
2023-11-03 18:24:41,467 - ERROR - :
2023-11-03 18:24:41,467 - ERROR - Text.insert() got an unexpected keyword argument 'fg'
2023-11-03 18:25:07,321 - INFO - [1m[37mPrograma Iniciado às [31m18:25:07[0m
2023-11-03 18:25:07,365 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:25:07,365 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:25:17,553 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:25:17,553 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:25:17,553 - INFO - CORAL: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Guaianases e Estudantes , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:25:17,553 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:25:30,663 - ERROR - Traceback (most recent call last):
2023-11-03 18:25:30,664 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 422, in <module>
2023-11-03 18:25:30,664 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:25:30,664 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:25:30,665 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,665 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR - ^
2023-11-03 18:25:30,666 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:25:30,666 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:25:30,666 - ERROR - _tkinter
2023-11-03 18:25:30,666 - ERROR - .
2023-11-03 18:25:30,666 - ERROR - TclError
2023-11-03 18:25:30,666 - ERROR - :
2023-11-03 18:25:30,667 - ERROR - invalid command name ".!canvas"
2023-11-03 18:27:59,269 - INFO - [1m[37mPrograma Iniciado às [31m18:27:59[0m
2023-11-03 18:27:59,316 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:27:59,316 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:28:09,777 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:28:09,778 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:28:09,778 - INFO - CORAL: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Guaianases e Estudantes , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:28:09,778 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:28:15,808 - ERROR - Traceback (most recent call last):
2023-11-03 18:28:15,809 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 421, in <module>
2023-11-03 18:28:15,809 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:28:15,809 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:28:15,810 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:28:15,810 - ERROR - ^
2023-11-03 18:28:15,810 - ERROR - ^
2023-11-03 18:28:15,810 - ERROR - ^
2023-11-03 18:28:15,810 - ERROR - ^
2023-11-03 18:28:15,811 - ERROR - ^
2023-11-03 18:28:15,811 - ERROR - ^
2023-11-03 18:28:15,811 - ERROR - ^
2023-11-03 18:28:15,811 - ERROR - ^
2023-11-03 18:28:15,811 - ERROR - ^
2023-11-03 18:28:15,811 - ERROR - ^
2023-11-03 18:28:15,811 - ERROR - ^
2023-11-03 18:28:15,811 - ERROR - ^
2023-11-03 18:28:15,811 - ERROR - ^
2023-11-03 18:28:15,812 - ERROR - ^
2023-11-03 18:28:15,812 - ERROR - ^
2023-11-03 18:28:15,812 - ERROR - ^
2023-11-03 18:28:15,812 - ERROR - ^
2023-11-03 18:28:15,812 - ERROR - ^
2023-11-03 18:28:15,812 - ERROR - ^
2023-11-03 18:28:15,812 - ERROR - ^
2023-11-03 18:28:15,812 - ERROR - ^
2023-11-03 18:28:15,812 - ERROR - ^
2023-11-03 18:28:15,813 - ERROR - ^
2023-11-03 18:28:15,813 - ERROR - ^
2023-11-03 18:28:15,813 - ERROR - ^
2023-11-03 18:28:15,813 - ERROR - ^
2023-11-03 18:28:15,813 - ERROR - ^
2023-11-03 18:28:15,813 - ERROR - ^
2023-11-03 18:28:15,813 - ERROR - ^
2023-11-03 18:28:15,813 - ERROR - ^
2023-11-03 18:28:15,813 - ERROR - ^
2023-11-03 18:28:15,813 - ERROR - ^
2023-11-03 18:28:15,813 - ERROR - ^
2023-11-03 18:28:15,814 - ERROR - ^
2023-11-03 18:28:15,814 - ERROR - ^
2023-11-03 18:28:15,814 - ERROR - ^
2023-11-03 18:28:15,814 - ERROR - ^
2023-11-03 18:28:15,814 - ERROR - ^
2023-11-03 18:28:15,814 - ERROR - ^
2023-11-03 18:28:15,814 - ERROR - ^
2023-11-03 18:28:15,814 - ERROR - ^
2023-11-03 18:28:15,814 - ERROR - ^
2023-11-03 18:28:15,815 - ERROR - ^
2023-11-03 18:28:15,815 - ERROR - ^
2023-11-03 18:28:15,815 - ERROR - ^
2023-11-03 18:28:15,815 - ERROR - ^
2023-11-03 18:28:15,815 - ERROR - ^
2023-11-03 18:28:15,815 - ERROR - ^
2023-11-03 18:28:15,815 - ERROR - ^
2023-11-03 18:28:15,815 - ERROR - ^
2023-11-03 18:28:15,815 - ERROR - ^
2023-11-03 18:28:15,815 - ERROR - ^
2023-11-03 18:28:15,815 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:28:15,815 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:28:15,815 - ERROR - _tkinter
2023-11-03 18:28:15,815 - ERROR - .
2023-11-03 18:28:15,815 - ERROR - TclError
2023-11-03 18:28:15,815 - ERROR - :
2023-11-03 18:28:15,815 - ERROR - invalid command name ".!canvas"
2023-11-03 18:28:34,302 - ERROR - Traceback (most recent call last):
2023-11-03 18:28:34,302 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 113, in <module>
2023-11-03 18:28:34,303 - ERROR - text_widget.place(x=10, y=810, text="", anchor="se")  # Posiciona o widget Text na posição (50, 50)
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,303 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR - ^
2023-11-03 18:28:34,304 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2504, in place_configure
2023-11-03 18:28:34,304 - ERROR - self.tk.call(
2023-11-03 18:28:34,305 - ERROR - _tkinter
2023-11-03 18:28:34,305 - ERROR - .
2023-11-03 18:28:34,305 - ERROR - TclError
2023-11-03 18:28:34,305 - ERROR - :
2023-11-03 18:28:34,305 - ERROR - unknown option "-text"
2023-11-03 18:28:51,554 - ERROR - Traceback (most recent call last):
2023-11-03 18:28:51,554 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 113, in <module>
2023-11-03 18:28:51,554 - ERROR - text_widget.place(x=10, y=810, text="", anchor="se")  # Posiciona o widget Text na posição (50, 50)
2023-11-03 18:28:51,554 - ERROR - ^
2023-11-03 18:28:51,554 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,555 - ERROR - ^
2023-11-03 18:28:51,556 - ERROR - ^
2023-11-03 18:28:51,556 - ERROR - ^
2023-11-03 18:28:51,556 - ERROR - ^
2023-11-03 18:28:51,556 - ERROR - ^
2023-11-03 18:28:51,556 - ERROR - ^
2023-11-03 18:28:51,556 - ERROR - ^
2023-11-03 18:28:51,556 - ERROR - ^
2023-11-03 18:28:51,556 - ERROR - ^
2023-11-03 18:28:51,556 - ERROR - ^
2023-11-03 18:28:51,556 - ERROR - ^
2023-11-03 18:28:51,556 - ERROR - ^
2023-11-03 18:28:51,556 - ERROR - ^
2023-11-03 18:28:51,556 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2504, in place_configure
2023-11-03 18:28:51,556 - ERROR - self.tk.call(
2023-11-03 18:28:51,556 - ERROR - _tkinter
2023-11-03 18:28:51,556 - ERROR - .
2023-11-03 18:28:51,556 - ERROR - TclError
2023-11-03 18:28:51,556 - ERROR - :
2023-11-03 18:28:51,556 - ERROR - unknown option "-text"
2023-11-03 18:28:59,244 - INFO - [1m[37mPrograma Iniciado às [31m18:28:59[0m
2023-11-03 18:28:59,288 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:28:59,289 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:29:09,672 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:29:09,672 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:29:09,672 - INFO - CORAL: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Guaianases e Estudantes , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:29:09,672 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:29:14,693 - ERROR - Traceback (most recent call last):
2023-11-03 18:29:14,693 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 423, in <module>
2023-11-03 18:29:14,694 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:29:14,694 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:29:14,694 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:29:14,694 - ERROR - ^
2023-11-03 18:29:14,694 - ERROR - ^
2023-11-03 18:29:14,694 - ERROR - ^
2023-11-03 18:29:14,694 - ERROR - ^
2023-11-03 18:29:14,694 - ERROR - ^
2023-11-03 18:29:14,694 - ERROR - ^
2023-11-03 18:29:14,694 - ERROR - ^
2023-11-03 18:29:14,694 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,695 - ERROR - ^
2023-11-03 18:29:14,696 - ERROR - ^
2023-11-03 18:29:14,696 - ERROR - ^
2023-11-03 18:29:14,696 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:29:14,696 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:29:14,696 - ERROR - _tkinter
2023-11-03 18:29:14,696 - ERROR - .
2023-11-03 18:29:14,696 - ERROR - TclError
2023-11-03 18:29:14,696 - ERROR - :
2023-11-03 18:29:14,696 - ERROR - invalid command name ".!canvas"
2023-11-03 18:30:30,961 - INFO - [1m[37mPrograma Iniciado às [31m18:30:30[0m
2023-11-03 18:30:31,018 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:30:31,018 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:30:42,050 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:30:42,051 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:30:42,051 - INFO - CORAL: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Guaianases e Estudantes , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:30:42,051 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:30:48,961 - ERROR - Traceback (most recent call last):
2023-11-03 18:30:48,962 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 423, in <module>
2023-11-03 18:30:48,962 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:30:48,962 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:30:48,963 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:30:48,963 - ERROR - ^
2023-11-03 18:30:48,963 - ERROR - ^
2023-11-03 18:30:48,963 - ERROR - ^
2023-11-03 18:30:48,963 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,964 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR - ^
2023-11-03 18:30:48,965 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:30:48,966 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:30:48,966 - ERROR - _tkinter
2023-11-03 18:30:48,966 - ERROR - .
2023-11-03 18:30:48,966 - ERROR - TclError
2023-11-03 18:30:48,966 - ERROR - :
2023-11-03 18:30:48,966 - ERROR - invalid command name ".!canvas"
2023-11-03 18:31:19,325 - INFO - [1m[37mPrograma Iniciado às [31m18:31:19[0m
2023-11-03 18:31:19,370 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:31:19,371 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:31:29,672 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:31:29,672 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:31:29,672 - INFO - CORAL: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Guaianases e Estudantes , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:31:29,673 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:31:36,701 - ERROR - Traceback (most recent call last):
2023-11-03 18:31:36,702 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 422, in <module>
2023-11-03 18:31:36,702 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:31:36,702 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:31:36,703 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,703 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR - ^
2023-11-03 18:31:36,704 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:31:36,704 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:31:36,704 - ERROR - _tkinter
2023-11-03 18:31:36,704 - ERROR - .
2023-11-03 18:31:36,705 - ERROR - TclError
2023-11-03 18:31:36,705 - ERROR - :
2023-11-03 18:31:36,705 - ERROR - invalid command name ".!canvas"
2023-11-03 18:33:11,393 - INFO - [1m[37mPrograma Iniciado às [31m18:33:11[0m
2023-11-03 18:33:11,439 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:33:11,440 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:33:21,745 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:33:21,745 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:33:21,745 - INFO - CORAL: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Guaianases e Estudantes , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:33:21,745 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:33:37,470 - ERROR - Traceback (most recent call last):
2023-11-03 18:33:37,470 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 423, in <module>
2023-11-03 18:33:37,471 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:33:37,471 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:33:37,472 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:33:37,472 - ERROR - ^
2023-11-03 18:33:37,472 - ERROR - ^
2023-11-03 18:33:37,472 - ERROR - ^
2023-11-03 18:33:37,472 - ERROR - ^
2023-11-03 18:33:37,472 - ERROR - ^
2023-11-03 18:33:37,472 - ERROR - ^
2023-11-03 18:33:37,472 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,473 - ERROR - ^
2023-11-03 18:33:37,474 - ERROR - ^
2023-11-03 18:33:37,474 - ERROR - ^
2023-11-03 18:33:37,474 - ERROR - ^
2023-11-03 18:33:37,474 - ERROR - ^
2023-11-03 18:33:37,474 - ERROR - ^
2023-11-03 18:33:37,474 - ERROR - ^
2023-11-03 18:33:37,474 - ERROR - ^
2023-11-03 18:33:37,474 - ERROR - ^
2023-11-03 18:33:37,474 - ERROR - ^
2023-11-03 18:33:37,474 - ERROR - ^
2023-11-03 18:33:37,474 - ERROR - ^
2023-11-03 18:33:37,474 - ERROR - ^
2023-11-03 18:33:37,474 - ERROR - ^
2023-11-03 18:33:37,474 - ERROR - ^
2023-11-03 18:33:37,474 - ERROR - ^
2023-11-03 18:33:37,474 - ERROR - ^
2023-11-03 18:33:37,474 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:33:37,474 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:33:37,474 - ERROR - _tkinter
2023-11-03 18:33:37,474 - ERROR - .
2023-11-03 18:33:37,474 - ERROR - TclError
2023-11-03 18:33:37,474 - ERROR - :
2023-11-03 18:33:37,474 - ERROR - invalid command name ".!canvas"
2023-11-03 18:35:15,583 - INFO - [1m[37mPrograma Iniciado às [31m18:35:15[0m
2023-11-03 18:35:15,632 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:35:15,632 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:35:26,106 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:35:26,106 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:35:26,106 - INFO - CORAL: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Guaianases e Estudantes , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:35:26,107 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:35:33,290 - ERROR - Traceback (most recent call last):
2023-11-03 18:35:33,291 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 422, in <module>
2023-11-03 18:35:33,291 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:35:33,291 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:35:33,292 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:35:33,292 - ERROR - ^
2023-11-03 18:35:33,292 - ERROR - ^
2023-11-03 18:35:33,292 - ERROR - ^
2023-11-03 18:35:33,293 - ERROR - ^
2023-11-03 18:35:33,293 - ERROR - ^
2023-11-03 18:35:33,293 - ERROR - ^
2023-11-03 18:35:33,293 - ERROR - ^
2023-11-03 18:35:33,293 - ERROR - ^
2023-11-03 18:35:33,293 - ERROR - ^
2023-11-03 18:35:33,293 - ERROR - ^
2023-11-03 18:35:33,293 - ERROR - ^
2023-11-03 18:35:33,293 - ERROR - ^
2023-11-03 18:35:33,293 - ERROR - ^
2023-11-03 18:35:33,293 - ERROR - ^
2023-11-03 18:35:33,293 - ERROR - ^
2023-11-03 18:35:33,293 - ERROR - ^
2023-11-03 18:35:33,293 - ERROR - ^
2023-11-03 18:35:33,293 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR - ^
2023-11-03 18:35:33,294 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:35:33,295 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:35:33,295 - ERROR - _tkinter
2023-11-03 18:35:33,295 - ERROR - .
2023-11-03 18:35:33,295 - ERROR - TclError
2023-11-03 18:35:33,295 - ERROR - :
2023-11-03 18:35:33,295 - ERROR - invalid command name ".!canvas"
2023-11-03 18:35:46,962 - INFO - [1m[37mPrograma Iniciado às [31m18:35:46[0m
2023-11-03 18:35:47,020 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:35:47,020 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:35:57,362 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:35:57,362 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:35:57,362 - INFO - CORAL: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Guaianases e Estudantes , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:35:57,362 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:36:02,635 - ERROR - Traceback (most recent call last):
2023-11-03 18:36:02,635 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 422, in <module>
2023-11-03 18:36:02,635 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:36:02,635 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:36:02,636 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,636 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR - ^
2023-11-03 18:36:02,637 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:36:02,637 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:36:02,638 - ERROR - _tkinter
2023-11-03 18:36:02,638 - ERROR - .
2023-11-03 18:36:02,638 - ERROR - TclError
2023-11-03 18:36:02,638 - ERROR - :
2023-11-03 18:36:02,638 - ERROR - invalid command name ".!canvas"
2023-11-03 18:36:09,383 - INFO - [1m[37mPrograma Iniciado às [31m18:36:09[0m
2023-11-03 18:36:09,428 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:36:09,428 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:36:19,884 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:36:19,884 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:36:19,884 - INFO - CORAL: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Guaianases e Estudantes , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:36:19,884 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:36:24,080 - ERROR - Traceback (most recent call last):
2023-11-03 18:36:24,080 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 422, in <module>
2023-11-03 18:36:24,081 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:36:24,081 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:36:24,081 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:36:24,081 - ERROR - ^
2023-11-03 18:36:24,081 - ERROR - ^
2023-11-03 18:36:24,081 - ERROR - ^
2023-11-03 18:36:24,081 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,082 - ERROR - ^
2023-11-03 18:36:24,083 - ERROR - ^
2023-11-03 18:36:24,083 - ERROR - ^
2023-11-03 18:36:24,083 - ERROR - ^
2023-11-03 18:36:24,083 - ERROR - ^
2023-11-03 18:36:24,083 - ERROR - ^
2023-11-03 18:36:24,083 - ERROR - ^
2023-11-03 18:36:24,083 - ERROR - ^
2023-11-03 18:36:24,083 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:36:24,083 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:36:24,083 - ERROR - _tkinter
2023-11-03 18:36:24,083 - ERROR - .
2023-11-03 18:36:24,083 - ERROR - TclError
2023-11-03 18:36:24,083 - ERROR - :
2023-11-03 18:36:24,083 - ERROR - invalid command name ".!canvas"
2023-11-03 18:36:33,718 - INFO - [1m[37mPrograma Iniciado às [31m18:36:33[0m
2023-11-03 18:36:33,763 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:36:33,763 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:36:44,154 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:36:44,154 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:36:44,154 - INFO - CORAL: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Guaianases e Estudantes , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:36:44,154 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:36:47,421 - ERROR - Traceback (most recent call last):
2023-11-03 18:36:47,421 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 422, in <module>
2023-11-03 18:36:47,421 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:36:47,421 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:36:47,422 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,422 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR - ^
2023-11-03 18:36:47,423 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:36:47,424 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:36:47,424 - ERROR - _tkinter
2023-11-03 18:36:47,424 - ERROR - .
2023-11-03 18:36:47,424 - ERROR - TclError
2023-11-03 18:36:47,424 - ERROR - :
2023-11-03 18:36:47,424 - ERROR - invalid command name ".!canvas"
2023-11-03 18:37:01,876 - INFO - [1m[37mPrograma Iniciado às [31m18:37:01[0m
2023-11-03 18:37:01,932 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:37:01,932 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:37:12,351 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:37:12,351 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:37:12,351 - INFO - CORAL: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Guaianases e Estudantes , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:37:12,351 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:37:24,649 - ERROR - Traceback (most recent call last):
2023-11-03 18:37:24,649 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 422, in <module>
2023-11-03 18:37:24,650 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:37:24,650 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:37:24,650 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,651 - ERROR - ^
2023-11-03 18:37:24,652 - ERROR - ^
2023-11-03 18:37:24,652 - ERROR - ^
2023-11-03 18:37:24,652 - ERROR - ^
2023-11-03 18:37:24,652 - ERROR - ^
2023-11-03 18:37:24,652 - ERROR - ^
2023-11-03 18:37:24,652 - ERROR - ^
2023-11-03 18:37:24,652 - ERROR - ^
2023-11-03 18:37:24,652 - ERROR - ^
2023-11-03 18:37:24,652 - ERROR - ^
2023-11-03 18:37:24,652 - ERROR - ^
2023-11-03 18:37:24,652 - ERROR - ^
2023-11-03 18:37:24,652 - ERROR - ^
2023-11-03 18:37:24,652 - ERROR - ^
2023-11-03 18:37:24,652 - ERROR - ^
2023-11-03 18:37:24,652 - ERROR - ^
2023-11-03 18:37:24,652 - ERROR - ^
2023-11-03 18:37:24,652 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:37:24,652 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:37:24,652 - ERROR - _tkinter
2023-11-03 18:37:24,652 - ERROR - .
2023-11-03 18:37:24,652 - ERROR - TclError
2023-11-03 18:37:24,652 - ERROR - :
2023-11-03 18:37:24,652 - ERROR - invalid command name ".!canvas"
2023-11-03 18:38:23,826 - INFO - [1m[37mPrograma Iniciado às [31m18:38:23[0m
2023-11-03 18:38:23,882 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:38:23,882 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:38:34,245 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:38:34,245 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:38:34,245 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:38:52,863 - ERROR - Traceback (most recent call last):
2023-11-03 18:38:52,864 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 422, in <module>
2023-11-03 18:38:52,864 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:38:52,864 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:38:52,865 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:38:52,865 - ERROR - ^
2023-11-03 18:38:52,865 - ERROR - ^
2023-11-03 18:38:52,866 - ERROR - ^
2023-11-03 18:38:52,866 - ERROR - ^
2023-11-03 18:38:52,866 - ERROR - ^
2023-11-03 18:38:52,866 - ERROR - ^
2023-11-03 18:38:52,866 - ERROR - ^
2023-11-03 18:38:52,866 - ERROR - ^
2023-11-03 18:38:52,866 - ERROR - ^
2023-11-03 18:38:52,866 - ERROR - ^
2023-11-03 18:38:52,866 - ERROR - ^
2023-11-03 18:38:52,866 - ERROR - ^
2023-11-03 18:38:52,867 - ERROR - ^
2023-11-03 18:38:52,867 - ERROR - ^
2023-11-03 18:38:52,867 - ERROR - ^
2023-11-03 18:38:52,867 - ERROR - ^
2023-11-03 18:38:52,867 - ERROR - ^
2023-11-03 18:38:52,867 - ERROR - ^
2023-11-03 18:38:52,867 - ERROR - ^
2023-11-03 18:38:52,867 - ERROR - ^
2023-11-03 18:38:52,867 - ERROR - ^
2023-11-03 18:38:52,867 - ERROR - ^
2023-11-03 18:38:52,867 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR - ^
2023-11-03 18:38:52,868 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:38:52,869 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:38:52,869 - ERROR - _tkinter
2023-11-03 18:38:52,869 - ERROR - .
2023-11-03 18:38:52,869 - ERROR - TclError
2023-11-03 18:38:52,869 - ERROR - :
2023-11-03 18:38:52,869 - ERROR - invalid command name ".!canvas"
2023-11-03 18:39:17,032 - ERROR - Traceback (most recent call last):
2023-11-03 18:39:17,033 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 112, in <module>
2023-11-03 18:39:17,033 - ERROR - text_widget.pack(relx=0, rely=0.81, relwidth=1, relheight=0.19)
2023-11-03 18:39:17,033 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2452, in pack_configure
2023-11-03 18:39:17,033 - ERROR - self.tk.call(
2023-11-03 18:39:17,033 - ERROR - _tkinter
2023-11-03 18:39:17,033 - ERROR - .
2023-11-03 18:39:17,034 - ERROR - TclError
2023-11-03 18:39:17,034 - ERROR - :
2023-11-03 18:39:17,034 - ERROR - bad option "-relx": must be -after, -anchor, -before, -expand, -fill, -in, -ipadx, -ipady, -padx, -pady, or -side
2023-11-03 18:41:15,122 - INFO - [1m[37mPrograma Iniciado às [31m18:41:15[0m
2023-11-03 18:41:15,182 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:41:15,182 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:41:25,681 - ERROR - Traceback (most recent call last):
2023-11-03 18:41:25,682 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 421, in <module>
2023-11-03 18:41:25,682 - ERROR - atualizar_status()
2023-11-03 18:41:25,682 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 101, in atualizar_status
2023-11-03 18:41:25,683 - ERROR - label.config('end', mensagem + '\n')
2023-11-03 18:41:25,683 - ERROR - TypeError
2023-11-03 18:41:25,683 - ERROR - :
2023-11-03 18:41:25,683 - ERROR - Misc.configure() takes from 1 to 2 positional arguments but 3 were given
2023-11-03 18:41:57,464 - INFO - [1m[37mPrograma Iniciado às [31m18:41:57[0m
2023-11-03 18:41:57,509 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:41:57,509 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:42:08,021 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:42:08,022 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:42:08,023 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:42:13,199 - ERROR - Traceback (most recent call last):
2023-11-03 18:42:13,200 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 424, in <module>
2023-11-03 18:42:13,200 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:42:13,200 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:42:13,201 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,201 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR - ^
2023-11-03 18:42:13,202 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:42:13,202 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:42:13,202 - ERROR - _tkinter
2023-11-03 18:42:13,203 - ERROR - .
2023-11-03 18:42:13,203 - ERROR - TclError
2023-11-03 18:42:13,203 - ERROR - :
2023-11-03 18:42:13,203 - ERROR - invalid command name ".!canvas"
2023-11-03 18:45:28,429 - INFO - [1m[37mPrograma Iniciado às [31m18:45:28[0m
2023-11-03 18:45:28,475 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:45:28,475 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:45:39,190 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:45:39,190 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:45:39,191 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:45:46,139 - ERROR - Traceback (most recent call last):
2023-11-03 18:45:46,139 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 423, in <module>
2023-11-03 18:45:46,139 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:45:46,139 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:45:46,140 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,140 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR - ^
2023-11-03 18:45:46,141 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:45:46,142 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:45:46,142 - ERROR - _tkinter
2023-11-03 18:45:46,142 - ERROR - .
2023-11-03 18:45:46,142 - ERROR - TclError
2023-11-03 18:45:46,142 - ERROR - :
2023-11-03 18:45:46,142 - ERROR - invalid command name ".!canvas"
2023-11-03 18:48:49,103 - INFO - [1m[37mPrograma Iniciado às [31m18:48:49[0m
2023-11-03 18:48:49,154 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:48:49,154 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:48:59,751 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:48:59,751 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:48:59,752 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:49:07,671 - ERROR - Traceback (most recent call last):
2023-11-03 18:49:07,672 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 417, in <module>
2023-11-03 18:49:07,672 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:49:07,673 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:49:07,673 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:49:07,673 - ERROR - ^
2023-11-03 18:49:07,673 - ERROR - ^
2023-11-03 18:49:07,673 - ERROR - ^
2023-11-03 18:49:07,673 - ERROR - ^
2023-11-03 18:49:07,673 - ERROR - ^
2023-11-03 18:49:07,673 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,674 - ERROR - ^
2023-11-03 18:49:07,675 - ERROR - ^
2023-11-03 18:49:07,675 - ERROR - ^
2023-11-03 18:49:07,675 - ERROR - ^
2023-11-03 18:49:07,675 - ERROR - ^
2023-11-03 18:49:07,675 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:49:07,675 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:49:07,675 - ERROR - _tkinter
2023-11-03 18:49:07,675 - ERROR - .
2023-11-03 18:49:07,675 - ERROR - TclError
2023-11-03 18:49:07,675 - ERROR - :
2023-11-03 18:49:07,675 - ERROR - invalid command name ".!canvas"
2023-11-03 18:49:43,196 - INFO - [1m[37mPrograma Iniciado às [31m18:49:43[0m
2023-11-03 18:49:43,241 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:49:43,241 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:49:54,090 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:49:54,091 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:49:54,091 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:50:03,407 - ERROR - Traceback (most recent call last):
2023-11-03 18:50:03,407 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 417, in <module>
2023-11-03 18:50:03,407 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:50:03,408 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:50:03,408 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,409 - ERROR - ^
2023-11-03 18:50:03,410 - ERROR - ^
2023-11-03 18:50:03,410 - ERROR - ^
2023-11-03 18:50:03,410 - ERROR - ^
2023-11-03 18:50:03,410 - ERROR - ^
2023-11-03 18:50:03,410 - ERROR - ^
2023-11-03 18:50:03,410 - ERROR - ^
2023-11-03 18:50:03,410 - ERROR - ^
2023-11-03 18:50:03,410 - ERROR - ^
2023-11-03 18:50:03,410 - ERROR - ^
2023-11-03 18:50:03,410 - ERROR - ^
2023-11-03 18:50:03,410 - ERROR - ^
2023-11-03 18:50:03,410 - ERROR - ^
2023-11-03 18:50:03,410 - ERROR - ^
2023-11-03 18:50:03,410 - ERROR - ^
2023-11-03 18:50:03,410 - ERROR - ^
2023-11-03 18:50:03,410 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:50:03,410 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:50:03,410 - ERROR - _tkinter
2023-11-03 18:50:03,410 - ERROR - .
2023-11-03 18:50:03,410 - ERROR - TclError
2023-11-03 18:50:03,410 - ERROR - :
2023-11-03 18:50:03,410 - ERROR - invalid command name ".!canvas"
2023-11-03 18:50:09,945 - INFO - [1m[37mPrograma Iniciado às [31m18:50:09[0m
2023-11-03 18:50:09,993 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:50:09,993 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:50:20,921 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:50:20,922 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:50:20,922 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:50:28,728 - ERROR - Traceback (most recent call last):
2023-11-03 18:50:28,728 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 417, in <module>
2023-11-03 18:50:28,728 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:50:28,728 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:50:28,729 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,729 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR - ^
2023-11-03 18:50:28,730 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:50:28,731 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:50:28,731 - ERROR - _tkinter
2023-11-03 18:50:28,731 - ERROR - .
2023-11-03 18:50:28,731 - ERROR - TclError
2023-11-03 18:50:28,731 - ERROR - :
2023-11-03 18:50:28,731 - ERROR - invalid command name ".!canvas"
2023-11-03 18:50:35,884 - INFO - [1m[37mPrograma Iniciado às [31m18:50:35[0m
2023-11-03 18:50:35,931 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:50:35,931 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:50:46,321 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:50:46,321 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:50:46,321 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:50:50,063 - ERROR - Traceback (most recent call last):
2023-11-03 18:50:50,064 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 417, in <module>
2023-11-03 18:50:50,064 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:50:50,064 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:50:50,065 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:50:50,065 - ERROR - ^
2023-11-03 18:50:50,065 - ERROR - ^
2023-11-03 18:50:50,065 - ERROR - ^
2023-11-03 18:50:50,065 - ERROR - ^
2023-11-03 18:50:50,065 - ERROR - ^
2023-11-03 18:50:50,065 - ERROR - ^
2023-11-03 18:50:50,065 - ERROR - ^
2023-11-03 18:50:50,065 - ERROR - ^
2023-11-03 18:50:50,065 - ERROR - ^
2023-11-03 18:50:50,065 - ERROR - ^
2023-11-03 18:50:50,065 - ERROR - ^
2023-11-03 18:50:50,065 - ERROR - ^
2023-11-03 18:50:50,065 - ERROR - ^
2023-11-03 18:50:50,065 - ERROR - ^
2023-11-03 18:50:50,065 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR - ^
2023-11-03 18:50:50,066 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:50:50,067 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:50:50,067 - ERROR - _tkinter
2023-11-03 18:50:50,067 - ERROR - .
2023-11-03 18:50:50,067 - ERROR - TclError
2023-11-03 18:50:50,067 - ERROR - :
2023-11-03 18:50:50,067 - ERROR - invalid command name ".!canvas"
2023-11-03 18:51:50,138 - INFO - [1m[37mPrograma Iniciado às [31m18:51:50[0m
2023-11-03 18:51:50,184 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:51:50,184 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:52:01,647 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:52:01,647 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:52:01,648 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:52:09,851 - ERROR - Traceback (most recent call last):
2023-11-03 18:52:09,851 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 419, in <module>
2023-11-03 18:52:09,851 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:52:09,852 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:52:09,853 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:52:09,853 - ERROR - ^
2023-11-03 18:52:09,853 - ERROR - ^
2023-11-03 18:52:09,853 - ERROR - ^
2023-11-03 18:52:09,853 - ERROR - ^
2023-11-03 18:52:09,853 - ERROR - ^
2023-11-03 18:52:09,853 - ERROR - ^
2023-11-03 18:52:09,854 - ERROR - ^
2023-11-03 18:52:09,854 - ERROR - ^
2023-11-03 18:52:09,854 - ERROR - ^
2023-11-03 18:52:09,854 - ERROR - ^
2023-11-03 18:52:09,854 - ERROR - ^
2023-11-03 18:52:09,854 - ERROR - ^
2023-11-03 18:52:09,854 - ERROR - ^
2023-11-03 18:52:09,854 - ERROR - ^
2023-11-03 18:52:09,854 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,855 - ERROR - ^
2023-11-03 18:52:09,856 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:52:09,856 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:52:09,856 - ERROR - _tkinter
2023-11-03 18:52:09,856 - ERROR - .
2023-11-03 18:52:09,856 - ERROR - TclError
2023-11-03 18:52:09,856 - ERROR - :
2023-11-03 18:52:09,856 - ERROR - invalid command name ".!canvas"
2023-11-03 18:52:54,684 - INFO - [1m[37mPrograma Iniciado às [31m18:52:54[0m
2023-11-03 18:52:54,729 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:52:54,729 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:53:05,003 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:53:05,004 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:53:05,004 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:53:12,819 - ERROR - Traceback (most recent call last):
2023-11-03 18:53:12,820 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 419, in <module>
2023-11-03 18:53:12,820 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:53:12,820 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:53:12,821 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:53:12,821 - ERROR - ^
2023-11-03 18:53:12,821 - ERROR - ^
2023-11-03 18:53:12,821 - ERROR - ^
2023-11-03 18:53:12,821 - ERROR - ^
2023-11-03 18:53:12,822 - ERROR - ^
2023-11-03 18:53:12,822 - ERROR - ^
2023-11-03 18:53:12,822 - ERROR - ^
2023-11-03 18:53:12,822 - ERROR - ^
2023-11-03 18:53:12,822 - ERROR - ^
2023-11-03 18:53:12,822 - ERROR - ^
2023-11-03 18:53:12,822 - ERROR - ^
2023-11-03 18:53:12,822 - ERROR - ^
2023-11-03 18:53:12,822 - ERROR - ^
2023-11-03 18:53:12,822 - ERROR - ^
2023-11-03 18:53:12,823 - ERROR - ^
2023-11-03 18:53:12,823 - ERROR - ^
2023-11-03 18:53:12,823 - ERROR - ^
2023-11-03 18:53:12,823 - ERROR - ^
2023-11-03 18:53:12,823 - ERROR - ^
2023-11-03 18:53:12,823 - ERROR - ^
2023-11-03 18:53:12,823 - ERROR - ^
2023-11-03 18:53:12,823 - ERROR - ^
2023-11-03 18:53:12,823 - ERROR - ^
2023-11-03 18:53:12,823 - ERROR - ^
2023-11-03 18:53:12,823 - ERROR - ^
2023-11-03 18:53:12,823 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR - ^
2023-11-03 18:53:12,824 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:53:12,825 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:53:12,825 - ERROR - _tkinter
2023-11-03 18:53:12,825 - ERROR - .
2023-11-03 18:53:12,825 - ERROR - TclError
2023-11-03 18:53:12,825 - ERROR - :
2023-11-03 18:53:12,825 - ERROR - invalid command name ".!canvas"
2023-11-03 18:53:29,831 - INFO - [1m[37mPrograma Iniciado às [31m18:53:29[0m
2023-11-03 18:53:29,879 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:53:29,879 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:53:40,117 - ERROR - Traceback (most recent call last):
2023-11-03 18:53:40,117 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 415, in <module>
2023-11-03 18:53:40,118 - ERROR - atualizar_status()
2023-11-03 18:53:40,118 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 100, in atualizar_status
2023-11-03 18:53:40,118 - ERROR - mensagens = '\n'.join(lista_mensagens, anchor='se')
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,118 - ERROR - ^
2023-11-03 18:53:40,119 - ERROR - ^
2023-11-03 18:53:40,119 - ERROR - ^
2023-11-03 18:53:40,119 - ERROR - ^
2023-11-03 18:53:40,119 - ERROR - ^
2023-11-03 18:53:40,119 - ERROR - ^
2023-11-03 18:53:40,119 - ERROR - ^
2023-11-03 18:53:40,119 - ERROR - ^
2023-11-03 18:53:40,119 - ERROR - ^
2023-11-03 18:53:40,119 - ERROR - ^
2023-11-03 18:53:40,119 - ERROR - ^
2023-11-03 18:53:40,119 - ERROR - TypeError
2023-11-03 18:53:40,119 - ERROR - :
2023-11-03 18:53:40,119 - ERROR - str.join() takes no keyword arguments
2023-11-03 18:53:56,335 - INFO - [1m[37mPrograma Iniciado às [31m18:53:56[0m
2023-11-03 18:53:56,382 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-03 18:53:56,382 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-03 18:54:06,834 - INFO - Linha 8-Diamante: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:54:06,834 - INFO - Linha 9-Esmeralda: Devido as condições climáticas, os trens estão circulando com velocidade reduzida e maior tempo de parada.
2023-11-03 18:54:06,834 - INFO - SAFIRA: Estamos circulando com velocidade reduzida e maior tempo de parada entre as Estações Brás e Calmon Viana , devido a Descarga Elétrica Atmosférica . Agradecemos a sua compreensão
2023-11-03 18:54:22,493 - ERROR - Traceback (most recent call last):
2023-11-03 18:54:22,493 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 418, in <module>
2023-11-03 18:54:22,494 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-03 18:54:22,494 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-03 18:54:22,494 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,495 - ERROR - ^
2023-11-03 18:54:22,496 - ERROR - ^
2023-11-03 18:54:22,496 - ERROR - ^
2023-11-03 18:54:22,496 - ERROR - ^
2023-11-03 18:54:22,496 - ERROR - ^
2023-11-03 18:54:22,496 - ERROR - ^
2023-11-03 18:54:22,496 - ERROR - ^
2023-11-03 18:54:22,496 - ERROR - ^
2023-11-03 18:54:22,496 - ERROR - ^
2023-11-03 18:54:22,496 - ERROR - ^
2023-11-03 18:54:22,496 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-03 18:54:22,496 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-03 18:54:22,496 - ERROR - _tkinter
2023-11-03 18:54:22,496 - ERROR - .
2023-11-03 18:54:22,496 - ERROR - TclError
2023-11-03 18:54:22,496 - ERROR - :
2023-11-03 18:54:22,496 - ERROR - invalid command name ".!canvas"
2023-11-08 15:16:18,424 - INFO - [1m[37mPrograma Iniciado às [31m15:16:18[0m
2023-11-08 15:16:18,566 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-08 15:16:18,567 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-08 15:16:30,997 - INFO - Nenhuma ocorrência no momento.
2023-11-08 15:16:41,846 - ERROR - Traceback (most recent call last):
2023-11-08 15:16:41,846 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 418, in <module>
2023-11-08 15:16:41,848 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-08 15:16:41,848 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-08 15:16:41,864 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,864 - ERROR - ^
2023-11-08 15:16:41,865 - ERROR - ^
2023-11-08 15:16:41,865 - ERROR - ^
2023-11-08 15:16:41,865 - ERROR - ^
2023-11-08 15:16:41,865 - ERROR - ^
2023-11-08 15:16:41,865 - ERROR - ^
2023-11-08 15:16:41,865 - ERROR - ^
2023-11-08 15:16:41,865 - ERROR - ^
2023-11-08 15:16:41,865 - ERROR - ^
2023-11-08 15:16:41,865 - ERROR - ^
2023-11-08 15:16:41,865 - ERROR - ^
2023-11-08 15:16:41,865 - ERROR - ^
2023-11-08 15:16:41,865 - ERROR - ^
2023-11-08 15:16:41,865 - ERROR - ^
2023-11-08 15:16:41,865 - ERROR - ^
2023-11-08 15:16:41,865 - ERROR - ^
2023-11-08 15:16:41,865 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-08 15:16:41,865 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-08 15:16:41,865 - ERROR - _tkinter
2023-11-08 15:16:41,865 - ERROR - .
2023-11-08 15:16:41,865 - ERROR - TclError
2023-11-08 15:16:41,865 - ERROR - :
2023-11-08 15:16:41,865 - ERROR - invalid command name ".!canvas"
2023-11-09 13:04:42,007 - INFO - [1m[37mPrograma Iniciado às [31m13:04:42[0m
2023-11-09 13:04:42,288 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-09 13:04:42,289 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-09 13:04:57,085 - INFO - Linha 5-Lilás: Devido a falha no sistema elétrico os trens estão operando por via única entre as estações Santo Amaro e Brooklin. PAESE acionado para minimizar os impactos para os clientes.
2023-11-09 13:05:32,693 - ERROR - Traceback (most recent call last):
2023-11-09 13:05:32,693 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 418, in <module>
2023-11-09 13:05:32,696 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-09 13:05:32,696 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-09 13:05:32,721 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-09 13:05:32,721 - ERROR - ^
2023-11-09 13:05:32,721 - ERROR - ^
2023-11-09 13:05:32,721 - ERROR - ^
2023-11-09 13:05:32,721 - ERROR - ^
2023-11-09 13:05:32,721 - ERROR - ^
2023-11-09 13:05:32,721 - ERROR - ^
2023-11-09 13:05:32,721 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,722 - ERROR - ^
2023-11-09 13:05:32,723 - ERROR - ^
2023-11-09 13:05:32,723 - ERROR - ^
2023-11-09 13:05:32,723 - ERROR - ^
2023-11-09 13:05:32,723 - ERROR - ^
2023-11-09 13:05:32,723 - ERROR - ^
2023-11-09 13:05:32,723 - ERROR - ^
2023-11-09 13:05:32,723 - ERROR - ^
2023-11-09 13:05:32,723 - ERROR - ^
2023-11-09 13:05:32,723 - ERROR - ^
2023-11-09 13:05:32,723 - ERROR - ^
2023-11-09 13:05:32,723 - ERROR - ^
2023-11-09 13:05:32,723 - ERROR - ^
2023-11-09 13:05:32,723 - ERROR - ^
2023-11-09 13:05:32,723 - ERROR - ^
2023-11-09 13:05:32,723 - ERROR - ^
2023-11-09 13:05:32,723 - ERROR - ^
2023-11-09 13:05:32,723 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-09 13:05:32,724 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-09 13:05:32,724 - ERROR - _tkinter
2023-11-09 13:05:32,724 - ERROR - .
2023-11-09 13:05:32,724 - ERROR - TclError
2023-11-09 13:05:32,724 - ERROR - :
2023-11-09 13:05:32,724 - ERROR - invalid command name ".!canvas"
2023-11-13 09:49:39,352 - INFO - [1m[37mPrograma Iniciado às [31m09:49:39[0m
2023-11-13 09:49:39,522 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-13 09:49:39,522 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-13 09:49:52,798 - INFO - Nenhuma ocorrência no momento.
2023-11-13 09:55:49,880 - ERROR - Traceback (most recent call last):
2023-11-13 09:55:49,880 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 418, in <module>
2023-11-13 09:55:49,882 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-13 09:55:49,883 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-13 09:55:49,927 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-13 09:55:49,927 - ERROR - ^
2023-11-13 09:55:49,927 - ERROR - ^
2023-11-13 09:55:49,928 - ERROR - ^
2023-11-13 09:55:49,928 - ERROR - ^
2023-11-13 09:55:49,928 - ERROR - ^
2023-11-13 09:55:49,928 - ERROR - ^
2023-11-13 09:55:49,929 - ERROR - ^
2023-11-13 09:55:49,929 - ERROR - ^
2023-11-13 09:55:49,929 - ERROR - ^
2023-11-13 09:55:49,930 - ERROR - ^
2023-11-13 09:55:49,930 - ERROR - ^
2023-11-13 09:55:49,930 - ERROR - ^
2023-11-13 09:55:49,931 - ERROR - ^
2023-11-13 09:55:49,931 - ERROR - ^
2023-11-13 09:55:49,931 - ERROR - ^
2023-11-13 09:55:49,931 - ERROR - ^
2023-11-13 09:55:49,932 - ERROR - ^
2023-11-13 09:55:49,932 - ERROR - ^
2023-11-13 09:55:49,932 - ERROR - ^
2023-11-13 09:55:49,932 - ERROR - ^
2023-11-13 09:55:49,932 - ERROR - ^
2023-11-13 09:55:49,932 - ERROR - ^
2023-11-13 09:55:49,932 - ERROR - ^
2023-11-13 09:55:49,932 - ERROR - ^
2023-11-13 09:55:49,932 - ERROR - ^
2023-11-13 09:55:49,932 - ERROR - ^
2023-11-13 09:55:49,932 - ERROR - ^
2023-11-13 09:55:49,932 - ERROR - ^
2023-11-13 09:55:49,932 - ERROR - ^
2023-11-13 09:55:49,932 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,933 - ERROR - ^
2023-11-13 09:55:49,934 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-13 09:55:49,935 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-13 09:55:49,935 - ERROR - _tkinter
2023-11-13 09:55:49,935 - ERROR - .
2023-11-13 09:55:49,935 - ERROR - TclError
2023-11-13 09:55:49,935 - ERROR - :
2023-11-13 09:55:49,935 - ERROR - invalid command name ".!canvas"
2023-11-14 13:56:23,159 - INFO - [1m[37mPrograma Iniciado às [31m13:56:23[0m
2023-11-14 13:56:23,264 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-14 13:56:23,264 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-14 13:56:37,349 - INFO - Nenhuma ocorrência no momento.
2023-11-14 13:56:47,430 - INFO - [1m[37mMapa iniciado às [32m13:56:22[37m, aguarde[0m
2023-11-14 13:59:47,185 - ERROR - Traceback (most recent call last):
2023-11-14 13:59:47,193 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 418, in <module>
2023-11-14 13:59:47,201 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-14 13:59:47,204 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-14 13:59:47,253 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-14 13:59:47,255 - ERROR - ^
2023-11-14 13:59:47,257 - ERROR - ^
2023-11-14 13:59:47,257 - ERROR - ^
2023-11-14 13:59:47,257 - ERROR - ^
2023-11-14 13:59:47,258 - ERROR - ^
2023-11-14 13:59:47,258 - ERROR - ^
2023-11-14 13:59:47,258 - ERROR - ^
2023-11-14 13:59:47,258 - ERROR - ^
2023-11-14 13:59:47,259 - ERROR - ^
2023-11-14 13:59:47,259 - ERROR - ^
2023-11-14 13:59:47,259 - ERROR - ^
2023-11-14 13:59:47,259 - ERROR - ^
2023-11-14 13:59:47,259 - ERROR - ^
2023-11-14 13:59:47,259 - ERROR - ^
2023-11-14 13:59:47,259 - ERROR - ^
2023-11-14 13:59:47,260 - ERROR - ^
2023-11-14 13:59:47,260 - ERROR - ^
2023-11-14 13:59:47,260 - ERROR - ^
2023-11-14 13:59:47,260 - ERROR - ^
2023-11-14 13:59:47,260 - ERROR - ^
2023-11-14 13:59:47,260 - ERROR - ^
2023-11-14 13:59:47,261 - ERROR - ^
2023-11-14 13:59:47,261 - ERROR - ^
2023-11-14 13:59:47,261 - ERROR - ^
2023-11-14 13:59:47,261 - ERROR - ^
2023-11-14 13:59:47,261 - ERROR - ^
2023-11-14 13:59:47,261 - ERROR - ^
2023-11-14 13:59:47,262 - ERROR - ^
2023-11-14 13:59:47,262 - ERROR - ^
2023-11-14 13:59:47,262 - ERROR - ^
2023-11-14 13:59:47,262 - ERROR - ^
2023-11-14 13:59:47,262 - ERROR - ^
2023-11-14 13:59:47,263 - ERROR - ^
2023-11-14 13:59:47,263 - ERROR - ^
2023-11-14 13:59:47,263 - ERROR - ^
2023-11-14 13:59:47,264 - ERROR - ^
2023-11-14 13:59:47,264 - ERROR - ^
2023-11-14 13:59:47,264 - ERROR - ^
2023-11-14 13:59:47,264 - ERROR - ^
2023-11-14 13:59:47,264 - ERROR - ^
2023-11-14 13:59:47,264 - ERROR - ^
2023-11-14 13:59:47,264 - ERROR - ^
2023-11-14 13:59:47,264 - ERROR - ^
2023-11-14 13:59:47,264 - ERROR - ^
2023-11-14 13:59:47,264 - ERROR - ^
2023-11-14 13:59:47,264 - ERROR - ^
2023-11-14 13:59:47,264 - ERROR - ^
2023-11-14 13:59:47,264 - ERROR - ^
2023-11-14 13:59:47,264 - ERROR - ^
2023-11-14 13:59:47,264 - ERROR - ^
2023-11-14 13:59:47,265 - ERROR - ^
2023-11-14 13:59:47,265 - ERROR - ^
2023-11-14 13:59:47,265 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-14 13:59:47,266 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-14 13:59:47,267 - ERROR - _tkinter
2023-11-14 13:59:47,267 - ERROR - .
2023-11-14 13:59:47,267 - ERROR - TclError
2023-11-14 13:59:47,268 - ERROR - :
2023-11-14 13:59:47,268 - ERROR - invalid command name ".!canvas"
2023-11-28 09:38:38,960 - INFO - [1m[37mPrograma Iniciado às [31m09:38:38[0m
2023-11-28 09:38:39,117 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-28 09:38:39,117 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-28 09:39:00,357 - INFO - Linha 1 - Azul: - Devido à greve dos Metroviários o Metrô de São Paulo está operando parcialmente, entre as estações TIRADENTES e ANA ROSA. Mais informações ligue para 0800 7707722.
2023-11-28 09:39:00,359 - INFO - Linha 2 - Verde: - Devido à greve dos Metroviários o Metrô de São Paulo está operando parcialmente, entre as estações ALTO DO IPIRANGA e CLÍNICAS. Mais informações ligue para 0800 7707722.
2023-11-28 09:39:00,362 - INFO - Linha 3 - Vermelha: - Devido à greve dos Metroviários o Metrô de São Paulo está operando parcialmente, entre as estações BRESSER e SANTA CECÍLIA. Mais informações ligue para 0800 7707722.
2023-11-28 09:39:00,364 - INFO - RUBI: Por motivo de greve os trens da linha 7-Rubi estão circulando entre a estação Luz e a estação Caieiras
2023-11-28 09:39:00,365 - INFO - TURQUESA: Por motivo de greve os trens da linha 10-Turquesa não estão operando.
2023-11-28 09:39:00,367 - INFO - CORAL: Por motivo de greve os trens da linha 11 Coral estão circulando somente entre as estações Luz e Guaianazes e com maiores intervalos.
2023-11-28 09:39:00,367 - INFO - Linha 15 - Prata: Devido à greve dos metroviários a circulação de trens está paralisada.
2023-11-28 09:43:56,680 - ERROR - Traceback (most recent call last):
2023-11-28 09:43:56,682 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 418, in <module>
2023-11-28 09:43:56,684 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-28 09:43:56,685 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-28 09:43:56,687 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-28 09:43:56,687 - ERROR - ^
2023-11-28 09:43:56,688 - ERROR - ^
2023-11-28 09:43:56,688 - ERROR - ^
2023-11-28 09:43:56,689 - ERROR - ^
2023-11-28 09:43:56,689 - ERROR - ^
2023-11-28 09:43:56,689 - ERROR - ^
2023-11-28 09:43:56,689 - ERROR - ^
2023-11-28 09:43:56,690 - ERROR - ^
2023-11-28 09:43:56,690 - ERROR - ^
2023-11-28 09:43:56,690 - ERROR - ^
2023-11-28 09:43:56,691 - ERROR - ^
2023-11-28 09:43:56,691 - ERROR - ^
2023-11-28 09:43:56,691 - ERROR - ^
2023-11-28 09:43:56,692 - ERROR - ^
2023-11-28 09:43:56,692 - ERROR - ^
2023-11-28 09:43:56,692 - ERROR - ^
2023-11-28 09:43:56,693 - ERROR - ^
2023-11-28 09:43:56,693 - ERROR - ^
2023-11-28 09:43:56,693 - ERROR - ^
2023-11-28 09:43:56,693 - ERROR - ^
2023-11-28 09:43:56,694 - ERROR - ^
2023-11-28 09:43:56,695 - ERROR - ^
2023-11-28 09:43:56,695 - ERROR - ^
2023-11-28 09:43:56,695 - ERROR - ^
2023-11-28 09:43:56,695 - ERROR - ^
2023-11-28 09:43:56,695 - ERROR - ^
2023-11-28 09:43:56,695 - ERROR - ^
2023-11-28 09:43:56,696 - ERROR - ^
2023-11-28 09:43:56,696 - ERROR - ^
2023-11-28 09:43:56,696 - ERROR - ^
2023-11-28 09:43:56,696 - ERROR - ^
2023-11-28 09:43:56,696 - ERROR - ^
2023-11-28 09:43:56,696 - ERROR - ^
2023-11-28 09:43:56,696 - ERROR - ^
2023-11-28 09:43:56,696 - ERROR - ^
2023-11-28 09:43:56,696 - ERROR - ^
2023-11-28 09:43:56,696 - ERROR - ^
2023-11-28 09:43:56,697 - ERROR - ^
2023-11-28 09:43:56,697 - ERROR - ^
2023-11-28 09:43:56,697 - ERROR - ^
2023-11-28 09:43:56,697 - ERROR - ^
2023-11-28 09:43:56,697 - ERROR - ^
2023-11-28 09:43:56,697 - ERROR - ^
2023-11-28 09:43:56,697 - ERROR - ^
2023-11-28 09:43:56,697 - ERROR - ^
2023-11-28 09:43:56,697 - ERROR - ^
2023-11-28 09:43:56,697 - ERROR - ^
2023-11-28 09:43:56,697 - ERROR - ^
2023-11-28 09:43:56,698 - ERROR - ^
2023-11-28 09:43:56,698 - ERROR - ^
2023-11-28 09:43:56,698 - ERROR - ^
2023-11-28 09:43:56,698 - ERROR - ^
2023-11-28 09:43:56,698 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-28 09:43:56,699 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-28 09:43:56,699 - ERROR - _tkinter
2023-11-28 09:43:56,700 - ERROR - .
2023-11-28 09:43:56,700 - ERROR - TclError
2023-11-28 09:43:56,700 - ERROR - :
2023-11-28 09:43:56,700 - ERROR - invalid command name ".!canvas"
2023-11-29 09:27:27,976 - INFO - [1m[37mPrograma Iniciado às [31m09:27:27[0m
2023-11-29 09:27:28,178 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-11-29 09:27:28,179 - ERROR -   warnings.warn("Image was not the expected size")
2023-11-29 09:27:42,629 - INFO - Nenhuma ocorrência no momento.
2023-11-29 09:28:05,605 - ERROR - Traceback (most recent call last):
2023-11-29 09:28:05,605 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 418, in <module>
2023-11-29 09:28:05,608 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-11-29 09:28:05,609 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-11-29 09:28:05,635 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-11-29 09:28:05,635 - ERROR - ^
2023-11-29 09:28:05,636 - ERROR - ^
2023-11-29 09:28:05,636 - ERROR - ^
2023-11-29 09:28:05,636 - ERROR - ^
2023-11-29 09:28:05,636 - ERROR - ^
2023-11-29 09:28:05,636 - ERROR - ^
2023-11-29 09:28:05,636 - ERROR - ^
2023-11-29 09:28:05,637 - ERROR - ^
2023-11-29 09:28:05,637 - ERROR - ^
2023-11-29 09:28:05,637 - ERROR - ^
2023-11-29 09:28:05,637 - ERROR - ^
2023-11-29 09:28:05,637 - ERROR - ^
2023-11-29 09:28:05,638 - ERROR - ^
2023-11-29 09:28:05,638 - ERROR - ^
2023-11-29 09:28:05,638 - ERROR - ^
2023-11-29 09:28:05,638 - ERROR - ^
2023-11-29 09:28:05,638 - ERROR - ^
2023-11-29 09:28:05,639 - ERROR - ^
2023-11-29 09:28:05,639 - ERROR - ^
2023-11-29 09:28:05,639 - ERROR - ^
2023-11-29 09:28:05,639 - ERROR - ^
2023-11-29 09:28:05,639 - ERROR - ^
2023-11-29 09:28:05,639 - ERROR - ^
2023-11-29 09:28:05,640 - ERROR - ^
2023-11-29 09:28:05,640 - ERROR - ^
2023-11-29 09:28:05,640 - ERROR - ^
2023-11-29 09:28:05,640 - ERROR - ^
2023-11-29 09:28:05,640 - ERROR - ^
2023-11-29 09:28:05,641 - ERROR - ^
2023-11-29 09:28:05,641 - ERROR - ^
2023-11-29 09:28:05,641 - ERROR - ^
2023-11-29 09:28:05,642 - ERROR - ^
2023-11-29 09:28:05,642 - ERROR - ^
2023-11-29 09:28:05,642 - ERROR - ^
2023-11-29 09:28:05,642 - ERROR - ^
2023-11-29 09:28:05,642 - ERROR - ^
2023-11-29 09:28:05,643 - ERROR - ^
2023-11-29 09:28:05,643 - ERROR - ^
2023-11-29 09:28:05,643 - ERROR - ^
2023-11-29 09:28:05,643 - ERROR - ^
2023-11-29 09:28:05,643 - ERROR - ^
2023-11-29 09:28:05,644 - ERROR - ^
2023-11-29 09:28:05,644 - ERROR - ^
2023-11-29 09:28:05,644 - ERROR - ^
2023-11-29 09:28:05,644 - ERROR - ^
2023-11-29 09:28:05,644 - ERROR - ^
2023-11-29 09:28:05,644 - ERROR - ^
2023-11-29 09:28:05,644 - ERROR - ^
2023-11-29 09:28:05,644 - ERROR - ^
2023-11-29 09:28:05,644 - ERROR - ^
2023-11-29 09:28:05,644 - ERROR - ^
2023-11-29 09:28:05,644 - ERROR - ^
2023-11-29 09:28:05,644 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-11-29 09:28:05,645 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-11-29 09:28:05,645 - ERROR - _tkinter
2023-11-29 09:28:05,645 - ERROR - .
2023-11-29 09:28:05,645 - ERROR - TclError
2023-11-29 09:28:05,645 - ERROR - :
2023-11-29 09:28:05,645 - ERROR - invalid command name ".!canvas"
2023-12-10 14:42:03,509 - INFO - [1m[37mPrograma Iniciado às [31m14:42:03[0m
2023-12-10 14:42:03,607 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-12-10 14:42:03,607 - ERROR -   warnings.warn("Image was not the expected size")
2023-12-10 14:42:40,792 - INFO - Linha 3 - Vermelha: Devido a obras de melhoria na via, a circulação de trens na Linha 3 - Vermelha está com velocidade reduzida e maior tempo de parada nas estações.
2023-12-10 14:43:06,266 - ERROR - Traceback (most recent call last):
2023-12-10 14:43:06,266 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 418, in <module>
2023-12-10 14:43:06,266 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-12-10 14:43:06,266 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-12-10 14:43:06,282 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-12-10 14:43:06,282 - ERROR - ^
2023-12-10 14:43:06,282 - ERROR - ^
2023-12-10 14:43:06,282 - ERROR - ^
2023-12-10 14:43:06,282 - ERROR - ^
2023-12-10 14:43:06,282 - ERROR - ^
2023-12-10 14:43:06,282 - ERROR - ^
2023-12-10 14:43:06,282 - ERROR - ^
2023-12-10 14:43:06,282 - ERROR - ^
2023-12-10 14:43:06,282 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR - ^
2023-12-10 14:43:06,292 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-12-10 14:43:06,292 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-12-10 14:43:06,292 - ERROR - _tkinter
2023-12-10 14:43:06,292 - ERROR - .
2023-12-10 14:43:06,292 - ERROR - TclError
2023-12-10 14:43:06,292 - ERROR - :
2023-12-10 14:43:06,292 - ERROR - invalid command name ".!canvas"
2023-12-27 02:19:53,511 - INFO - [1m[37mPrograma Iniciado às [31m02:19:53[0m
2023-12-27 02:19:53,619 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-12-27 02:19:53,619 - ERROR -   warnings.warn("Image was not the expected size")
2023-12-27 02:20:28,237 - INFO - Linha 1 - Azul: Fora do Horário de Operação
2023-12-27 02:20:28,237 - INFO - Linha 2 - Verde: Fora do Horário de Operação
2023-12-27 02:20:28,237 - INFO - Linha 3 - Vermelha: Fora do Horário de Operação
2023-12-27 02:20:28,238 - INFO - Linha 15 - Prata: Fora do Horário de Operação
2023-12-27 02:22:02,086 - ERROR - Traceback (most recent call last):
2023-12-27 02:22:02,087 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 418, in <module>
2023-12-27 02:22:02,088 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-12-27 02:22:02,089 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-12-27 02:22:02,109 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-12-27 02:22:02,109 - ERROR - ^
2023-12-27 02:22:02,109 - ERROR - ^
2023-12-27 02:22:02,109 - ERROR - ^
2023-12-27 02:22:02,110 - ERROR - ^
2023-12-27 02:22:02,110 - ERROR - ^
2023-12-27 02:22:02,110 - ERROR - ^
2023-12-27 02:22:02,110 - ERROR - ^
2023-12-27 02:22:02,110 - ERROR - ^
2023-12-27 02:22:02,110 - ERROR - ^
2023-12-27 02:22:02,110 - ERROR - ^
2023-12-27 02:22:02,110 - ERROR - ^
2023-12-27 02:22:02,110 - ERROR - ^
2023-12-27 02:22:02,110 - ERROR - ^
2023-12-27 02:22:02,110 - ERROR - ^
2023-12-27 02:22:02,111 - ERROR - ^
2023-12-27 02:22:02,111 - ERROR - ^
2023-12-27 02:22:02,111 - ERROR - ^
2023-12-27 02:22:02,111 - ERROR - ^
2023-12-27 02:22:02,111 - ERROR - ^
2023-12-27 02:22:02,111 - ERROR - ^
2023-12-27 02:22:02,111 - ERROR - ^
2023-12-27 02:22:02,111 - ERROR - ^
2023-12-27 02:22:02,111 - ERROR - ^
2023-12-27 02:22:02,111 - ERROR - ^
2023-12-27 02:22:02,111 - ERROR - ^
2023-12-27 02:22:02,112 - ERROR - ^
2023-12-27 02:22:02,112 - ERROR - ^
2023-12-27 02:22:02,112 - ERROR - ^
2023-12-27 02:22:02,112 - ERROR - ^
2023-12-27 02:22:02,112 - ERROR - ^
2023-12-27 02:22:02,112 - ERROR - ^
2023-12-27 02:22:02,112 - ERROR - ^
2023-12-27 02:22:02,112 - ERROR - ^
2023-12-27 02:22:02,112 - ERROR - ^
2023-12-27 02:22:02,112 - ERROR - ^
2023-12-27 02:22:02,112 - ERROR - ^
2023-12-27 02:22:02,113 - ERROR - ^
2023-12-27 02:22:02,113 - ERROR - ^
2023-12-27 02:22:02,113 - ERROR - ^
2023-12-27 02:22:02,113 - ERROR - ^
2023-12-27 02:22:02,113 - ERROR - ^
2023-12-27 02:22:02,113 - ERROR - ^
2023-12-27 02:22:02,113 - ERROR - ^
2023-12-27 02:22:02,113 - ERROR - ^
2023-12-27 02:22:02,113 - ERROR - ^
2023-12-27 02:22:02,113 - ERROR - ^
2023-12-27 02:22:02,113 - ERROR - ^
2023-12-27 02:22:02,114 - ERROR - ^
2023-12-27 02:22:02,114 - ERROR - ^
2023-12-27 02:22:02,114 - ERROR - ^
2023-12-27 02:22:02,114 - ERROR - ^
2023-12-27 02:22:02,114 - ERROR - ^
2023-12-27 02:22:02,114 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-12-27 02:22:02,115 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-12-27 02:22:02,115 - ERROR - _tkinter
2023-12-27 02:22:02,115 - ERROR - .
2023-12-27 02:22:02,115 - ERROR - TclError
2023-12-27 02:22:02,116 - ERROR - :
2023-12-27 02:22:02,116 - ERROR - invalid command name ".!canvas"
